In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
label_path = '/content/drive/MyDrive/MOOCCubeX/Dataset/Data_cleaned/Label_3_and_5_classes(have_course_info).csv'
user_problem_path = '/content/drive/MyDrive/MOOCCubeX/Dataset/Data_cleaned/Exercise/user-problem_cleaned.parquet'
problem_path = '/content/drive/MyDrive/MOOCCubeX/Dataset/Data_cleaned/Exercise/problem_df_cleaned.parquet'

In [3]:
import pandas as pd

In [4]:
label = pd.read_csv(label_path)
label.head()

,course_id,start_date,end_date,assignment,video,exam,course_duration,user_id,enroll_time,enrollment_to_end,...,average_correct_ratio_exam,amount_exercise_each_assignment,total_correct_ratio_assignment,average_correct_ratio_assignment,watched_videos,video_counts,watch_percent,score,label_3,label_5
0,C_2033958,2020-09-04,2020-12-31,40.0,30.0,30.0,118,U_10000,2020-10-27 09:07:30,64,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,E,E
1,C_1925903,2020-08-12,2020-12-31,30.0,30.0,40.0,141,U_1000129,2020-09-06 14:37:17,115,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,E,E
2,C_1992970,2020-08-27,2020-12-31,30.0,30.0,40.0,126,U_1000129,2020-09-06 14:45:37,115,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,E,E
3,C_680884,2020-09-01,2020-12-31,80.0,20.0,0.0,121,U_1000129,2020-10-16 10:41:09,75,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,E,E
4,C_697791,2020-01-20,2020-07-31,80.0,20.0,0.0,193,U_1000342,2020-02-28 10:27:22,153,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,E,E

In [5]:
label.shape

(2324544, 22)

In [6]:
user_problem = pd.read_parquet(user_problem_path)
user_problem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3590295 entries, 0 to 3590294
Data columns (total 16 columns):
 #   Column                 Dtype
---  ------                 -----
 0   problem_id             object
 1   attempts               int64
 2   is_correct             int64
 3   log_id                 object
 4   score                  float64
 5   submit_time            object
 6   user_id                object
 7   type_1                 int64
 8   type_2                 int64
 9   type_3                 int64
 10  type_4                 int64
 11  type_5                 int64
 12  type_6                 int64
 13  max_score_for_problem  float64
 14  exercise_id            object
 15  course_id              object
dtypes: float64(2), int64(8), object(6)
memory usage: 438.3+ MB

In [7]:
probelm_df = pd.read_parquet(problem_path)
probelm_df.head()

,problem_id,title,content,option,answer,score,typetext,location,context_id,exercise_id,language_Chinese,language_English,type_1,type_2,type_3,type_4,type_5,type_6,course_id
0,Pm_1730,第一课 导论与三家分晋--习题,1、《资治通鉴》卷1记载：智宣子将以瑶为后，智果曰：“……瑶之贤于人者五，其不逮者一也。美鬓...,"{'A': '武艺超群，精通射御之术', 'B': '礼贤下士，虚怀若谷', 'C': '反...","[""B""]",1.0,单选题,1.4,"[8045581, 8045582, 8045583]",Ex_856,1,0,1,0,0,0,0,0,C_584313
1,Pm_1731,第一课 导论与三家分晋--习题,2、《资治通鉴》是一部____史书。,"{'A': '纪传体', 'B': '编年体', 'C': '纪事本末体', 'D': '国...","[""B""]",1.0,单选题,1.4,"[8045581, 8045582, 8045583]",Ex_856,1,0,1,0,0,0,0,0,C_584313
2,Pm_1732,第一课 导论与三家分晋--习题,3、《资治通鉴》原名____，后由____赐名“资治通鉴”。,"{'A': '《通鉴》；宋神宗', 'B': '《通志》；宋徽宗', 'C': '《通鉴》；...","[""D""]",1.0,单选题,1.4,"[8045581, 8045582, 8045583]",Ex_856,1,0,1,0,0,0,0,0,C_584313
3,Pm_1733,第一课 导论与三家分晋--习题,4、“三家分晋”中“三家”具体指：,"{'A': '魏赵韩', 'B': '魏韩智', 'C': '赵韩智', 'D': '魏赵智'}","[""A""]",1.0,单选题,1.4,"[8045581, 8045582, 8045583]",Ex_856,1,0,1,0,0,0,0,0,C_584313
4,Pm_1734,第一课 导论与三家分晋--习题,5、智伯联合韩、魏的军队攻打赵氏时，赵襄子选择退守的阵地是：,"{'A': '邯郸', 'B': '长子', 'C': '晋阳', 'D': '皋狼'}","[""C""]",1.0,单选题,1.4,"[8045581, 8045582, 8045583]",Ex_856,1,0,1,0,0,0,0,0,C_584313

In [8]:
selected_label_col = ['user_id', 'course_id',	'enroll_time','enrollment_to_end']
selected_label = label[selected_label_col]
selected_label.head()

     user_id  course_id          enroll_time  enrollment_to_end
0    U_10000  C_2033958  2020-10-27 09:07:30                 64
1  U_1000129  C_1925903  2020-09-06 14:37:17                115
2  U_1000129  C_1992970  2020-09-06 14:45:37                115
3  U_1000129   C_680884  2020-10-16 10:41:09                 75
4  U_1000342   C_697791  2020-02-28 10:27:22                153

In [9]:
merge_col = ['course_id', 'user_id']
merge = pd.merge(selected_label, user_problem, on=merge_col, how='inner')
merge.head()

,user_id,course_id,enroll_time,enrollment_to_end,problem_id,attempts,is_correct,log_id,score,submit_time,type_1,type_2,type_3,type_4,type_5,type_6,max_score_for_problem,exercise_id
0,U_1000979,C_947149,2020-03-03 00:03:14,46,Pm_1742152,1,1,1000979_1742152,0.8,2020-05-19 14:45:46,1,0,0,0,0,0,0.8,Ex_1431539
1,U_1000979,C_947149,2020-03-03 00:03:14,46,Pm_1742146,1,1,1000979_1742146,0.8,2020-05-19 14:26:35,0,0,0,0,0,1,0.8,Ex_1431537
2,U_1000979,C_947149,2020-03-03 00:03:14,46,Pm_1742153,1,1,1000979_1742153,0.8,2020-05-19 14:29:44,0,0,0,0,0,1,0.8,Ex_1431541
3,U_1000979,C_947149,2020-03-03 00:03:14,46,Pm_1742150,1,1,1000979_1742150,0.8,2020-05-19 14:28:52,0,0,0,0,0,1,0.8,Ex_1431539
4,U_1000979,C_947149,2020-03-03 00:03:14,46,Pm_1742147,1,1,1000979_1742147,0.8,2020-05-19 14:26:53,1,0,0,0,0,0,0.8,Ex_1431537

In [10]:
merge.shape

(2526082, 18)

In [11]:
merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2526082 entries, 0 to 2526081
Data columns (total 18 columns):
 #   Column                 Dtype
---  ------                 -----
 0   user_id                object
 1   course_id              object
 2   enroll_time            object
 3   enrollment_to_end      int64
 4   problem_id             object
 5   attempts               int64
 6   is_correct             int64
 7   log_id                 object
 8   score                  float64
 9   submit_time            object
 10  type_1                 int64
 11  type_2                 int64
 12  type_3                 int64
 13  type_4                 int64
 14  type_5                 int64
 15  type_6                 int64
 16  max_score_for_problem  float64
 17  exercise_id            object
dtypes: float64(2), int64(9), object(7)
memory usage: 346.9+ MB

In [12]:
merge['submit_time'] = pd.to_datetime(merge['submit_time'])
merge['enroll_time'] = pd.to_datetime(merge['enroll_time'])
merge['duration_days'] = (merge['submit_time'] - merge['enroll_time']).dt.days
display(merge.head())

,user_id,course_id,enroll_time,enrollment_to_end,problem_id,attempts,is_correct,log_id,score,submit_time,type_1,type_2,type_3,type_4,type_5,type_6,max_score_for_problem,exercise_id,duration_days
0,U_1000979,C_947149,2020-03-03 00:03:14,46,Pm_1742152,1,1,1000979_1742152,0.8,2020-05-19 14:45:46,1,0,0,0,0,0,0.8,Ex_1431539,77
1,U_1000979,C_947149,2020-03-03 00:03:14,46,Pm_1742146,1,1,1000979_1742146,0.8,2020-05-19 14:26:35,0,0,0,0,0,1,0.8,Ex_1431537,77
2,U_1000979,C_947149,2020-03-03 00:03:14,46,Pm_1742153,1,1,1000979_1742153,0.8,2020-05-19 14:29:44,0,0,0,0,0,1,0.8,Ex_1431541,77
3,U_1000979,C_947149,2020-03-03 00:03:14,46,Pm_1742150,1,1,1000979_1742150,0.8,2020-05-19 14:28:52,0,0,0,0,0,1,0.8,Ex_1431539,77
4,U_1000979,C_947149,2020-03-03 00:03:14,46,Pm_1742147,1,1,1000979_1742147,0.8,2020-05-19 14:26:53,1,0,0,0,0,0,0.8,Ex_1431537,77

In [13]:
import numpy as np

merge_filtered = merge.copy()

# Chuyển type từ one-hot
type_cols = ['type_1', 'type_2', 'type_3', 'type_4', 'type_5', 'type_6']
merge_filtered['type'] = merge_filtered[type_cols].dot(range(1, 7))

# Tính tỷ lệ thời gian = (ngày đã học / tổng thời gian)
merge_filtered['time_ratio'] = merge_filtered['duration_days'] / merge_filtered['enrollment_to_end']

# Điều kiện để gán phase theo tỷ lệ
conditions = [
    merge_filtered['time_ratio'] <= 0.25,
    merge_filtered['time_ratio'] <= 0.50,
    merge_filtered['time_ratio'] <= 0.75,
    merge_filtered['time_ratio'] <= 0.9
]
choices = [1, 2, 3, 4]

merge_filtered['phase'] = np.select(conditions, choices, default=None)

display(merge_filtered[['duration_days', 'enrollment_to_end', 'time_ratio', 'phase']].head())

   duration_days  enrollment_to_end  time_ratio phase
0             77                 46    1.673913  None
1             77                 46    1.673913  None
2             77                 46    1.673913  None
3             77                 46    1.673913  None
4             77                 46    1.673913  None

In [15]:
# Loại bỏ những dòng có phase none
merge_filtered = merge_filtered.dropna(subset=['phase'])
merge_filtered.shape

(2035888, 22)

In [16]:
merge_filtered['phase'].value_counts()

phase
1    811342
3    546052
2    458628
4    219866
Name: count, dtype: int64

In [17]:
merge_phase_1 = merge_filtered[merge_filtered['phase'] == 1]
merge_phase_2 = merge_filtered[merge_filtered['phase'] == 2]
merge_phase_3 = merge_filtered[merge_filtered['phase'] == 3]
merge_phase_4 = merge_filtered[merge_filtered['phase'] == 4]

In [18]:
import numpy as np
group_by_col = ['user_id', 'course_id', 'exercise_id']

def calculate_average_time_between_submissions(submit_times):
    if len(submit_times) > 1:
        sorted_times = sorted(submit_times)
        diffs = [(sorted_times[i] - sorted_times[i-1]).total_seconds() for i in range(1, len(sorted_times))]
        return sum(diffs) / len(diffs)
    return 0

phases = [merge_phase_1, merge_phase_2, merge_phase_3, merge_phase_4]
grouped_results = []

for df in phases:
    df.loc[:, 'submit_time'] = pd.to_datetime(df['submit_time'])
    df.loc[:, 'enroll_time'] = pd.to_datetime(df['enroll_time'])
    grouped = df.groupby(group_by_col).agg(
        sum_attempts=('attempts', 'sum'),
        sum_score=('score', 'sum'),
        sum_max_score=('max_score_for_problem', 'sum'),
        submit_times=('submit_time', list),
        average_time_between_submissions=('submit_time', calculate_average_time_between_submissions),
        min_date_from_enrol_to_submit=('submit_time', 'min'),
        max_date_from_enrol_to_submit=('submit_time', 'max'),
        enroll_time=('enroll_time', 'first')
    ).reset_index()

    grouped['score_to_max_score_ratio'] = grouped['sum_score'] / grouped['sum_max_score'].replace(0, np.nan)
    grouped['enroll_to_first_submit_days'] = (grouped['min_date_from_enrol_to_submit'] - grouped['enroll_time']).dt.days
    grouped['enroll_to_last_submit_days'] = (grouped['max_date_from_enrol_to_submit'] - grouped['enroll_time']).dt.days
    grouped_results.append(grouped)

merge_phase_1_grouped, merge_phase_2_grouped, merge_phase_3_grouped, merge_phase_4_grouped = grouped_results

In [19]:
def calculate_exercise_time(submit_times):
    if len(submit_times) > 0:
        return (max(submit_times) - min(submit_times)).total_seconds()
    else:
        return 0

merge_phase_1_grouped['exercise_time'] = merge_phase_1_grouped['submit_times'].apply(calculate_exercise_time)
merge_phase_2_grouped['exercise_time'] = merge_phase_2_grouped['submit_times'].apply(calculate_exercise_time)
merge_phase_3_grouped['exercise_time'] = merge_phase_3_grouped['submit_times'].apply(calculate_exercise_time)
merge_phase_4_grouped['exercise_time'] = merge_phase_4_grouped['submit_times'].apply(calculate_exercise_time)

print(merge_phase_1_grouped.shape)
print(merge_phase_2_grouped.shape)
print(merge_phase_3_grouped.shape)
print(merge_phase_4_grouped.shape)

(123393, 15)
(78991, 15)
(85844, 15)
(37709, 15)

In [20]:
group_by_user_course = ['user_id', 'course_id']

merge_phase_1_aggregated = merge_phase_1_grouped.groupby(group_by_user_course).agg(
    average_attempts=('sum_attempts', 'mean'),
    sum_exercise=('exercise_id', 'count'),
    average_ratio=('score_to_max_score_ratio', 'mean'),
    average_exercise_time=('exercise_time', 'mean'),
    average_time_between_submissions=('average_time_between_submissions', 'mean'),
    average_enroll_to_first_submit_days=('enroll_to_first_submit_days', 'mean'),
    average_enroll_to_last_submit_days=('enroll_to_last_submit_days', 'mean')
).reset_index()

merge_phase_2_aggregated = merge_phase_2_grouped.groupby(group_by_user_course).agg(
    average_attempts=('sum_attempts', 'mean'),
    sum_exercise=('exercise_id', 'count'),
    average_ratio=('score_to_max_score_ratio', 'mean'),
    average_exercise_time=('exercise_time', 'mean'),
    average_time_between_submissions=('average_time_between_submissions', 'mean'),
    average_enroll_to_first_submit_days=('enroll_to_first_submit_days', 'mean'),
    average_enroll_to_last_submit_days=('enroll_to_last_submit_days', 'mean')
).reset_index()

merge_phase_3_aggregated = merge_phase_3_grouped.groupby(group_by_user_course).agg(
    average_attempts=('sum_attempts', 'mean'),
    sum_exercise=('exercise_id', 'count'),
    average_ratio=('score_to_max_score_ratio', 'mean'),
    average_exercise_time=('exercise_time', 'mean'),
    average_time_between_submissions=('average_time_between_submissions', 'mean'),
    average_enroll_to_first_submit_days=('enroll_to_first_submit_days', 'mean'),
    average_enroll_to_last_submit_days=('enroll_to_last_submit_days', 'mean')
).reset_index()

merge_phase_4_aggregated = merge_phase_4_grouped.groupby(group_by_user_course).agg(
    average_attempts=('sum_attempts', 'mean'),
    sum_exercise=('exercise_id', 'count'),
    average_ratio=('score_to_max_score_ratio', 'mean'),
    average_exercise_time=('exercise_time', 'mean'),
    average_time_between_submissions=('average_time_between_submissions', 'mean'),
    average_enroll_to_first_submit_days=('enroll_to_first_submit_days', 'mean'),
    average_enroll_to_last_submit_days=('enroll_to_last_submit_days', 'mean')
).reset_index()

display(merge_phase_1_aggregated.head())
display(merge_phase_2_aggregated.head())
display(merge_phase_3_aggregated.head())
display(merge_phase_4_aggregated.head())

,user_id,course_id,average_attempts,sum_exercise,average_ratio,average_exercise_time,average_time_between_submissions,average_enroll_to_first_submit_days,average_enroll_to_last_submit_days
0,U_1000982,C_947149,4.571429,7,0.171429,35.714286,9.892857,0.000000,0.000000
1,U_10031894,C_697684,9.950000,20,0.756410,12535.800000,1393.011806,2.600000,2.750000
2,U_10060973,C_735115,17.000000,1,0.750000,1205.000000,75.312500,0.000000,0.000000
3,U_10065697,C_681255,2.000000,1,1.000000,25.000000,25.000000,4.000000,4.000000
4,U_10074612,C_735342,17.888889,9,0.777778,1616.333333,85.070175,4.444444,4.555556

,user_id,course_id,average_attempts,sum_exercise,average_ratio,average_exercise_time,average_time_between_submissions,average_enroll_to_first_submit_days,average_enroll_to_last_submit_days
0,U_10074612,C_735342,15.333333,6,0.779274,233.333333,13.299278,27.000000,27.000000
1,U_10075060,C_735342,20.000000,5,0.880000,21587.400000,1136.178947,22.800000,23.000000
2,U_10095925,C_696695,4.000000,1,1.000000,266.000000,88.666667,3.000000,3.000000
3,U_10099706,C_735342,20.000000,1,0.800000,557.000000,29.315789,72.000000,72.000000
4,U_10125830,C_934534,7.000000,3,0.555916,49.333333,8.222222,45.333333,45.333333

,user_id,course_id,average_attempts,sum_exercise,average_ratio,average_exercise_time,average_time_between_submissions,average_enroll_to_first_submit_days,average_enroll_to_last_submit_days
0,U_10125830,C_934534,7.000,1,0.700000,48.000000,8.000000,60.000000,60.000000
1,U_10127123,C_934534,6.875,8,0.586079,46.875000,8.012500,59.500000,59.500000
2,U_10127138,C_934534,7.000,3,0.686869,149.333333,24.888889,76.000000,76.000000
3,U_10127167,C_934534,7.000,13,0.591464,57.923077,9.653846,64.692308,64.692308
4,U_10127175,C_934534,7.000,10,0.807005,255.100000,42.516667,59.500000,59.500000

,user_id,course_id,average_attempts,sum_exercise,average_ratio,average_exercise_time,average_time_between_submissions,average_enroll_to_first_submit_days,average_enroll_to_last_submit_days
0,U_10071599,C_682356,1.0,1,1.000000,0.000000,0.000000,84.000000,84.000000
1,U_10125830,C_934534,7.0,3,0.659091,50.333333,8.388889,85.333333,85.333333
2,U_10127138,C_934534,7.0,4,0.627040,330.500000,55.083333,86.000000,86.000000
3,U_10128005,C_934534,7.0,1,0.750000,97.000000,16.166667,32.000000,32.000000
4,U_10130400,C_934534,4.5,12,0.615389,22.916667,6.866667,87.000000,87.000000

In [21]:
print(merge_phase_1_aggregated.shape)
print(merge_phase_2_aggregated.shape)
print(merge_phase_3_aggregated.shape)
print(merge_phase_4_aggregated.shape)

(15138, 9)
(9159, 9)
(9120, 9)
(4708, 9)

In [22]:
resource_exercise_path = '/content/drive/MyDrive/MOOCCubeX/Dataset/Data_cleaned/Exercise/resource_exercise_course_have_problem_info.parquet'
resource_exercise = pd.read_parquet(resource_exercise_path)
resource_exercise.head()

,id,titles_chapter,title_exercise,chapter,ex_id,ex_counts
0,C_1017355,"[Unit 1 Introduction to Chinese Medicine, Unit...","[1.1 Brief History of Chinese Medicine, 2.1 Ba...","[0.1, 1.1, 2.1, 2.1.1, 3.1, 5.1, 6.1.1, 7.1, 7...","[Ex_1617853, Ex_1736572, Ex_1617861, Ex_161786...",9
1,C_1017419,"[第一讲 智慧政府：智慧金融, 第二讲 智慧政府：政务服务, 第五讲 智慧环境：智慧的污染治...","[智慧金融, 智慧公共服务, 生活中的智慧环保, 智慧公共安全, 智慧社区, 智慧教育与AI技术]","[2.3, 3.3, 6.3, 7.3, 8.3, 9.3]","[Ex_1618251, Ex_1618254, Ex_1618263, Ex_161826...",6
2,C_1025064,"[第1章 思想政治教育与思想政治教育学述要, 第2章 思想政治教育的发生与发展, 第3...","[第1章测验, 第2章测验, 第3章测验]","[0.6, 1.7, 2.4]","[Ex_1622556, Ex_1622566, Ex_1622574]",3
3,C_1025079,"[第一周, 第四周, 第五周, 第七周, 第八周]","[一、缠丝健身功功理测验, 二、核心分部缠丝功法测验, 三、肩臂联合缠丝功法测验, 四、胸背...","[1.5, 4.5, 5.5, 7.5, 8.3]","[Ex_1622993, Ex_1623006, Ex_1623011, Ex_162302...",5
4,C_1123848,[1 概述],[单元测试],[1.3],[Ex_1685437],1

In [23]:
merge_phase_1_merged = pd.merge(merge_phase_1_aggregated, resource_exercise[['id', 'ex_counts']], left_on='course_id', right_on='id', how='inner')
merge_phase_2_merged = pd.merge(merge_phase_2_aggregated, resource_exercise[['id', 'ex_counts']], left_on='course_id', right_on='id', how='inner')
merge_phase_3_merged = pd.merge(merge_phase_3_aggregated, resource_exercise[['id', 'ex_counts']], left_on='course_id', right_on='id', how='inner')
merge_phase_4_merged = pd.merge(merge_phase_4_aggregated, resource_exercise[['id', 'ex_counts']], left_on='course_id', right_on='id', how='inner')

merge_phase_1_merged['exercise_completion_ratio'] = merge_phase_1_merged['sum_exercise'] / merge_phase_1_merged['ex_counts']
merge_phase_2_merged['exercise_completion_ratio'] = merge_phase_2_merged['sum_exercise'] / merge_phase_2_merged['ex_counts']
merge_phase_3_merged['exercise_completion_ratio'] = merge_phase_3_merged['sum_exercise'] / merge_phase_3_merged['ex_counts']
merge_phase_4_merged['exercise_completion_ratio'] = merge_phase_4_merged['sum_exercise'] / merge_phase_4_merged['ex_counts']

display(merge_phase_1_merged.head())
display(merge_phase_2_merged.head())
display(merge_phase_3_merged.head())
display(merge_phase_4_merged.head())

,user_id,course_id,average_attempts,sum_exercise,average_ratio,average_exercise_time,average_time_between_submissions,average_enroll_to_first_submit_days,average_enroll_to_last_submit_days,id,ex_counts,exercise_completion_ratio
0,U_1000982,C_947149,4.571429,7,0.171429,35.714286,9.892857,0.000000,0.000000,C_947149,11,0.636364
1,U_10031894,C_697684,9.950000,20,0.756410,12535.800000,1393.011806,2.600000,2.750000,C_697684,20,1.000000
2,U_10060973,C_735115,17.000000,1,0.750000,1205.000000,75.312500,0.000000,0.000000,C_735115,11,0.090909
3,U_10065697,C_681255,2.000000,1,1.000000,25.000000,25.000000,4.000000,4.000000,C_681255,18,0.055556
4,U_10074612,C_735342,17.888889,9,0.777778,1616.333333,85.070175,4.444444,4.555556,C_735342,21,0.428571

,user_id,course_id,average_attempts,sum_exercise,average_ratio,average_exercise_time,average_time_between_submissions,average_enroll_to_first_submit_days,average_enroll_to_last_submit_days,id,ex_counts,exercise_completion_ratio
0,U_10074612,C_735342,15.333333,6,0.779274,233.333333,13.299278,27.000000,27.000000,C_735342,21,0.285714
1,U_10075060,C_735342,20.000000,5,0.880000,21587.400000,1136.178947,22.800000,23.000000,C_735342,21,0.238095
2,U_10095925,C_696695,4.000000,1,1.000000,266.000000,88.666667,3.000000,3.000000,C_696695,2,0.500000
3,U_10099706,C_735342,20.000000,1,0.800000,557.000000,29.315789,72.000000,72.000000,C_735342,21,0.047619
4,U_10125830,C_934534,7.000000,3,0.555916,49.333333,8.222222,45.333333,45.333333,C_934534,13,0.230769

,user_id,course_id,average_attempts,sum_exercise,average_ratio,average_exercise_time,average_time_between_submissions,average_enroll_to_first_submit_days,average_enroll_to_last_submit_days,id,ex_counts,exercise_completion_ratio
0,U_10125830,C_934534,7.000,1,0.700000,48.000000,8.000000,60.000000,60.000000,C_934534,13,0.076923
1,U_10127123,C_934534,6.875,8,0.586079,46.875000,8.012500,59.500000,59.500000,C_934534,13,0.615385
2,U_10127138,C_934534,7.000,3,0.686869,149.333333,24.888889,76.000000,76.000000,C_934534,13,0.230769
3,U_10127167,C_934534,7.000,13,0.591464,57.923077,9.653846,64.692308,64.692308,C_934534,13,1.000000
4,U_10127175,C_934534,7.000,10,0.807005,255.100000,42.516667,59.500000,59.500000,C_934534,13,0.769231

,user_id,course_id,average_attempts,sum_exercise,average_ratio,average_exercise_time,average_time_between_submissions,average_enroll_to_first_submit_days,average_enroll_to_last_submit_days,id,ex_counts,exercise_completion_ratio
0,U_10071599,C_682356,1.0,1,1.000000,0.000000,0.000000,84.000000,84.000000,C_682356,26,0.038462
1,U_10125830,C_934534,7.0,3,0.659091,50.333333,8.388889,85.333333,85.333333,C_934534,13,0.230769
2,U_10127138,C_934534,7.0,4,0.627040,330.500000,55.083333,86.000000,86.000000,C_934534,13,0.307692
3,U_10128005,C_934534,7.0,1,0.750000,97.000000,16.166667,32.000000,32.000000,C_934534,13,0.076923
4,U_10130400,C_934534,4.5,12,0.615389,22.916667,6.866667,87.000000,87.000000,C_934534,13,0.923077

In [24]:
# Define the columns to rename
cols_to_rename = [
    'average_attempts',
    'average_ratio',
    'average_exercise_time',
    'average_time_between_submissions',
    'average_enroll_to_first_submit_days',
    'average_enroll_to_last_submit_days',
    'exercise_completion_ratio'
]

# Rename columns for each phase
rename_mapping_1 = {col: f'{col}_1' for col in cols_to_rename}
rename_mapping_2 = {col: f'{col}_2' for col in cols_to_rename}
rename_mapping_3 = {col: f'{col}_3' for col in cols_to_rename}
rename_mapping_4 = {col: f'{col}_4' for col in cols_to_rename}

merge_phase_1_merged.rename(columns=rename_mapping_1, inplace=True)
merge_phase_2_merged.rename(columns=rename_mapping_2, inplace=True)
merge_phase_3_merged.rename(columns=rename_mapping_3, inplace=True)
merge_phase_4_merged.rename(columns=rename_mapping_4, inplace=True)

In [25]:


drop_col = ['sum_exercise', 'id', 'ex_counts']
merge_phase_1_merged.drop(drop_col, axis=1, inplace=True)
merge_phase_2_merged.drop(drop_col, axis=1, inplace=True)
merge_phase_3_merged.drop(drop_col, axis=1, inplace=True)
merge_phase_4_merged.drop(drop_col, axis=1, inplace=True)

display(merge_phase_1_merged.head())
display(merge_phase_2_merged.head())
display(merge_phase_3_merged.head())
display(merge_phase_4_merged.head())

,user_id,course_id,average_attempts_1,average_ratio_1,average_exercise_time_1,average_time_between_submissions_1,average_enroll_to_first_submit_days_1,average_enroll_to_last_submit_days_1,exercise_completion_ratio_1
0,U_1000982,C_947149,4.571429,0.171429,35.714286,9.892857,0.000000,0.000000,0.636364
1,U_10031894,C_697684,9.950000,0.756410,12535.800000,1393.011806,2.600000,2.750000,1.000000
2,U_10060973,C_735115,17.000000,0.750000,1205.000000,75.312500,0.000000,0.000000,0.090909
3,U_10065697,C_681255,2.000000,1.000000,25.000000,25.000000,4.000000,4.000000,0.055556
4,U_10074612,C_735342,17.888889,0.777778,1616.333333,85.070175,4.444444,4.555556,0.428571

,user_id,course_id,average_attempts_2,average_ratio_2,average_exercise_time_2,average_time_between_submissions_2,average_enroll_to_first_submit_days_2,average_enroll_to_last_submit_days_2,exercise_completion_ratio_2
0,U_10074612,C_735342,15.333333,0.779274,233.333333,13.299278,27.000000,27.000000,0.285714
1,U_10075060,C_735342,20.000000,0.880000,21587.400000,1136.178947,22.800000,23.000000,0.238095
2,U_10095925,C_696695,4.000000,1.000000,266.000000,88.666667,3.000000,3.000000,0.500000
3,U_10099706,C_735342,20.000000,0.800000,557.000000,29.315789,72.000000,72.000000,0.047619
4,U_10125830,C_934534,7.000000,0.555916,49.333333,8.222222,45.333333,45.333333,0.230769

,user_id,course_id,average_attempts_3,average_ratio_3,average_exercise_time_3,average_time_between_submissions_3,average_enroll_to_first_submit_days_3,average_enroll_to_last_submit_days_3,exercise_completion_ratio_3
0,U_10125830,C_934534,7.000,0.700000,48.000000,8.000000,60.000000,60.000000,0.076923
1,U_10127123,C_934534,6.875,0.586079,46.875000,8.012500,59.500000,59.500000,0.615385
2,U_10127138,C_934534,7.000,0.686869,149.333333,24.888889,76.000000,76.000000,0.230769
3,U_10127167,C_934534,7.000,0.591464,57.923077,9.653846,64.692308,64.692308,1.000000
4,U_10127175,C_934534,7.000,0.807005,255.100000,42.516667,59.500000,59.500000,0.769231

,user_id,course_id,average_attempts_4,average_ratio_4,average_exercise_time_4,average_time_between_submissions_4,average_enroll_to_first_submit_days_4,average_enroll_to_last_submit_days_4,exercise_completion_ratio_4
0,U_10071599,C_682356,1.0,1.000000,0.000000,0.000000,84.000000,84.000000,0.038462
1,U_10125830,C_934534,7.0,0.659091,50.333333,8.388889,85.333333,85.333333,0.230769
2,U_10127138,C_934534,7.0,0.627040,330.500000,55.083333,86.000000,86.000000,0.307692
3,U_10128005,C_934534,7.0,0.750000,97.000000,16.166667,32.000000,32.000000,0.076923
4,U_10130400,C_934534,4.5,0.615389,22.916667,6.866667,87.000000,87.000000,0.923077

In [26]:
# In so luong dong va cot cua moi phase
print(merge_phase_1_merged.shape)
print(merge_phase_2_merged.shape)
print(merge_phase_3_merged.shape)
print(merge_phase_4_merged.shape)

(15138, 9)
(9159, 9)
(9120, 9)
(4708, 9)

In [27]:
merge_phase_1_merged.to_csv('/content/drive/MyDrive/MOOCCubeX/Dataset/Data_cleaned/Exercise/code/merge_phase_1_merged.csv', index=False)
merge_phase_2_merged.to_csv('/content/drive/MyDrive/MOOCCubeX/Dataset/Data_cleaned/Exercise/code/merge_phase_2_merged.csv', index=False)
merge_phase_3_merged.to_csv('/content/drive/MyDrive/MOOCCubeX/Dataset/Data_cleaned/Exercise/code/merge_phase_3_merged.csv', index=False)
merge_phase_4_merged.to_csv('/content/drive/MyDrive/MOOCCubeX/Dataset/Data_cleaned/Exercise/code/merge_phase_4_merged.csv', index=False)