In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import polars as pl

csv_path = '/content/drive/MyDrive/DS317 (1)/combined_label3.csv'
polars_df = pl.read_csv(csv_path)

print(polars_df.head())

shape: (5, 181)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ user_id   ┆ course_id ┆ course_du ┆ start_dat ┆ … ┆ cmt_p4_po ┆ cmt_p4_ne ┆ cmt_p4_ne ┆ cmt_p4_s │
│ ---       ┆ ---       ┆ ration    ┆ e         ┆   ┆ sitive_ra ┆ utral_rat ┆ gative_ra ┆ entiment │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ tio_phase ┆ io_phase4 ┆ tio_phase ┆ _entropy │
│           ┆           ┆ i64       ┆ str       ┆   ┆ 4         ┆ ---       ┆ 4         ┆ _phase…  │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ U_10000   ┆ C_2033958 ┆ 118       ┆ 2020-09-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆           ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│ U_1000129 ┆ C_1925903 ┆ 141       ┆ 2020-08-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ U_1000129 ┆ C_1992970 ┆ 126       ┆ 2020-08-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆           ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│ U_1000129 ┆ C_680884  ┆ 121       ┆ 2020-09-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ U_1000342 ┆ C_697791  ┆ 193       ┆ 2020-01-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆           ┆ 0         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
# Display the head of the existing Polars DataFrame for easier viewing
display(polars_df.head())

shape: (5, 181)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ user_id   ┆ course_id ┆ course_du ┆ start_dat ┆ … ┆ cmt_p4_po ┆ cmt_p4_ne ┆ cmt_p4_ne ┆ cmt_p4_s │
│ ---       ┆ ---       ┆ ration    ┆ e         ┆   ┆ sitive_ra ┆ utral_rat ┆ gative_ra ┆ entiment │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ tio_phase ┆ io_phase4 ┆ tio_phase ┆ _entropy │
│           ┆           ┆ i64       ┆ str       ┆   ┆ 4         ┆ ---       ┆ 4         ┆ _phase…  │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ U_10000   ┆ C_2033958 ┆ 118       ┆ 2020-09-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆           ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│ U_1000129 ┆ C_1925903 ┆ 141       ┆ 2020-08-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ U_1000129 ┆ C_1992970 ┆ 126       ┆ 2020-08-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆           ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│ U_1000129 ┆ C_680884  ┆ 121       ┆ 2020-09-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ U_1000342 ┆ C_697791  ┆ 193       ┆ 2020-01-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆           ┆ 0         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
# Drop the 'school' column from the Polars DataFrame
polars_df = polars_df.drop('school')

# Display the head of the DataFrame to confirm the column has been removed
print(polars_df.head())

shape: (5, 180)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ user_id   ┆ course_id ┆ course_du ┆ start_dat ┆ … ┆ cmt_p4_po ┆ cmt_p4_ne ┆ cmt_p4_ne ┆ cmt_p4_s │
│ ---       ┆ ---       ┆ ration    ┆ e         ┆   ┆ sitive_ra ┆ utral_rat ┆ gative_ra ┆ entiment │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ tio_phase ┆ io_phase4 ┆ tio_phase ┆ _entropy │
│           ┆           ┆ i64       ┆ str       ┆   ┆ 4         ┆ ---       ┆ 4         ┆ _phase…  │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ U_10000   ┆ C_2033958 ┆ 118       ┆ 2020-09-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆           ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│ U_1000129 ┆ C_1925903 ┆ 141       ┆ 2020-08-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆          │
│ U_1000129 ┆ C_1992970 ┆ 126       ┆ 2020-08-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆           ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│ U_1000129 ┆ C_680884  ┆ 121       ┆ 2020-09-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│ U_1000342 ┆ C_697791  ┆ 193       ┆ 2020-01-2 ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆           ┆ 0         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
# Check if 'label_5' column exists in polars_df
if 'label_5' in polars_df.columns:
    print("Column 'label_5' exists in the DataFrame.")
else:
    print("Column 'label_5' does NOT exist in the DataFrame.")

# Check if 'label_3' column exists in polars_df
if 'label_3' in polars_df.columns:
    print("Column 'label_3' exists in the DataFrame.")
else:
    print("Column 'label_3' does NOT exist in the DataFrame.")

Column 'label_5' does NOT exist in the DataFrame.
Column 'label_3' exists in the DataFrame.

In [ ]:
import polars as pl

def process_date_columns(df: pl.DataFrame):
    if "start_date" not in df.columns:
        return df

    # 1) Convert start_date → Date
    df = df.with_columns(
        pl.col("start_date").str.strptime(pl.Date, strict=False)
    )

    # 2) Tạo các cột mới
    df = df.with_columns([
        pl.col("start_date").dt.year().alias("start_year"),
        pl.col("start_date").dt.month().alias("start_month"),
        pl.col("start_date").dt.day().alias("start_day"),
    ])

    # 3) Sắp xếp lại cột: đưa 3 cột mới ngay sau start_date
    cols = df.columns
    idx = cols.index("start_date")

    new_order = (
        cols[:idx+1] +                 # giữ các cột trước start_date
        ["start_year", "start_month", "start_day"] +  # chèn 3 cột mới
        [c for c in cols if c not in ["start_year", "start_month", "start_day"] and c not in cols[:idx+1]]
    )

    df = df.select(new_order)
    return df

df = process_date_columns(polars_df)
df = df.drop('start_date')

In [ ]:
df

shape: (2_324_524, 182)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ user_id   ┆ course_id ┆ course_du ┆ start_yea ┆ … ┆ cmt_p4_po ┆ cmt_p4_ne ┆ cmt_p4_ne ┆ cmt_p4_s │
│ ---       ┆ ---       ┆ ration    ┆ r         ┆   ┆ sitive_ra ┆ utral_rat ┆ gative_ra ┆ entiment │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ tio_phase ┆ io_phase4 ┆ tio_phase ┆ _entropy │
│           ┆           ┆ i64       ┆ i32       ┆   ┆ 4         ┆ ---       ┆ 4         ┆ _phase…  │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ U_10000   ┆ C_2033958 ┆ 118       ┆ 2020      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ U_1000129 ┆ C_1925903 ┆ 141       ┆ 2020      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ U_1000129 ┆ C_1992970 ┆ 126       ┆ 2020      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ U_1000129 ┆ C_680884  ┆ 121       ┆ 2020      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ U_1000342 ┆ C_697791  ┆ 193       ┆ 2020      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ U_999821  ┆ C_1774965 ┆ 491       ┆ 2020      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ U_999821  ┆ C_696724  ┆ 103       ┆ 2019      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ U_999856  ┆ C_696827  ┆ 97        ┆ 2019      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ U_999856  ┆ C_947252  ┆ 165       ┆ 2020      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ U_999861  ┆ C_947252  ┆ 48        ┆ 2019      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
import polars as pl


def label_encode_replace(df: pl.DataFrame, columns: list[str]):
    for col in columns:
        # 1) Lấy giá trị unique và sort để mapping ổn định
        unique_vals = df[col].unique().sort()

        # 2) Tạo mapping: string → số
        mapper = {val: i for i, val in enumerate(unique_vals)}

        # 3) Replace + ép kiểu số
        df = df.with_columns(
            pl.col(col)
            .replace(mapper)        # thay string thành số
            .cast(pl.Int64)         # ép về dạng numeric int
            .alias(col)
        )
    return df

df = label_encode_replace(df, ["name", "school_name", "user_id", "course_id", "label_3"])

In [ ]:
df

shape: (2_324_524, 182)
┌─────────┬───────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ user_id ┆ course_id ┆ course_dur ┆ start_yea ┆ … ┆ cmt_p4_po ┆ cmt_p4_ne ┆ cmt_p4_ne ┆ cmt_p4_se │
│ ---     ┆ ---       ┆ ation      ┆ r         ┆   ┆ sitive_ra ┆ utral_rat ┆ gative_ra ┆ ntiment_e │
│ i64     ┆ i64       ┆ ---        ┆ ---       ┆   ┆ tio_phase ┆ io_phase4 ┆ tio_phase ┆ ntropy_ph │
│         ┆           ┆ i64        ┆ i32       ┆   ┆ 4         ┆ ---       ┆ 4         ┆ ase…      │
│         ┆           ┆            ┆           ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---       │
│         ┆           ┆            ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ f64       │
╞═════════╪═══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0       ┆ 351       ┆ 118        ┆ 2020      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1       ┆ 312       ┆ 141        ┆ 2020      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1       ┆ 345       ┆ 126        ┆ 2020      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1       ┆ 570       ┆ 121        ┆ 2020      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2       ┆ 714       ┆ 193        ┆ 2020      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ …       ┆ …         ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 1176016 ┆ 124       ┆ 491        ┆ 2020      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1176016 ┆ 674       ┆ 103        ┆ 2019      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1176017 ┆ 676       ┆ 97         ┆ 2019      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1176017 ┆ 848       ┆ 165        ┆ 2020      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1176018 ┆ 848       ┆ 48         ┆ 2019      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
└─────────┴───────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
string_cols = [c for c, dtype in df.schema.items() if dtype == pl.Utf8]
print("String columns:", string_cols)

df = df.with_columns([
    pl.col(c).cast(pl.Float64).alias(c) for c in string_cols
])

String columns: ['ex_p2_average_attempts_2', 'ex_p2_average_ratio_2', 'ex_p2_average_exercise_time_2', 'ex_p2_average_time_between_submissions_2', 'ex_p2_average_enroll_to_first_submit_days_2', 'ex_p2_average_enroll_to_last_submit_days_2', 'ex_p2_exercise_completion_ratio_2', 'vid_p2_segment_duration_seconds_2', 'vid_p2_avg_segment_duration_2', 'vid_p2_avg_real_watch_time_2', 'vid_p2_segment_count_2', 'vid_p2_avg_playback_speed_2', 'vid_p2_avg_day_of_week_2', 'vid_p2_most_common_hour_2', 'vid_p2_most_common_day_2', 'vid_p2_unique_video_count_2', 'vid_p2_avg_segment_count_per_video_2', 'vid_p2_var_playback_speed_2', 'vid_p2_fast_forward_ratio_2', 'vid_p2_session_duration_std_2', 'ex_p3_average_attempts_3', 'ex_p3_average_ratio_3', 'ex_p3_average_exercise_time_3', 'ex_p3_average_time_between_submissions_3', 'ex_p3_average_enroll_to_first_submit_days_3', 'ex_p3_average_enroll_to_last_submit_days_3', 'ex_p3_exercise_completion_ratio_3', 'vid_p3_segment_duration_seconds_3', 'vid_p3_avg_segment_duration_3', 'vid_p3_avg_real_watch_time_3', 'vid_p3_segment_count_3', 'vid_p3_avg_playback_speed_3', 'vid_p3_avg_day_of_week_3', 'vid_p3_most_common_hour_3', 'vid_p3_most_common_day_3', 'vid_p3_unique_video_count_3', 'vid_p3_avg_segment_count_per_video_3', 'vid_p3_var_playback_speed_3', 'vid_p3_fast_forward_ratio_3', 'vid_p3_session_duration_std_3', 'cmt_p3_time_bin_phase3', 'cmt_p3_entropy_time_comment_phase3', 'cmt_p3_total_words_phase3', 'cmt_p3_total_negative_phase3', 'cmt_p3_total_neutral_phase3', 'cmt_p3_total_positive_phase3', 'cmt_p3_total_comments_phase3', 'cmt_p3_avg_comment_length_phase3', 'cmt_p3_std_comment_length_phase3', 'cmt_p3_max_comment_length_phase3', 'cmt_p3_text_diversity_phase3', 'cmt_p3_comment_days_active_phase3', 'cmt_p3_entropy_time_mean_phase3', 'cmt_p3_most_common_time_bin_phase3', 'cmt_p3_time_entropy_var_phase3', 'cmt_p3_positive_ratio_phase3', 'cmt_p3_neutral_ratio_phase3', 'cmt_p3_negative_ratio_phase3', 'cmt_p3_sentiment_entropy_phase3', 'ex_p4_average_attempts_4', 'ex_p4_average_ratio_4', 'ex_p4_average_exercise_time_4', 'ex_p4_average_time_between_submissions_4', 'ex_p4_average_enroll_to_first_submit_days_4', 'ex_p4_average_enroll_to_last_submit_days_4', 'ex_p4_exercise_completion_ratio_4', 'vid_p4_segment_duration_seconds_4', 'vid_p4_avg_segment_duration_4', 'vid_p4_avg_real_watch_time_4', 'vid_p4_segment_count_4', 'vid_p4_avg_playback_speed_4', 'vid_p4_avg_day_of_week_4', 'vid_p4_most_common_hour_4', 'vid_p4_most_common_day_4', 'vid_p4_unique_video_count_4', 'vid_p4_avg_segment_count_per_video_4', 'vid_p4_var_playback_speed_4', 'vid_p4_fast_forward_ratio_4', 'vid_p4_session_duration_std_4']

In [ ]:
df

shape: (2_324_524, 182)
┌─────────┬───────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ user_id ┆ course_id ┆ course_dur ┆ start_yea ┆ … ┆ cmt_p4_po ┆ cmt_p4_ne ┆ cmt_p4_ne ┆ cmt_p4_se │
│ ---     ┆ ---       ┆ ation      ┆ r         ┆   ┆ sitive_ra ┆ utral_rat ┆ gative_ra ┆ ntiment_e │
│ i64     ┆ i64       ┆ ---        ┆ ---       ┆   ┆ tio_phase ┆ io_phase4 ┆ tio_phase ┆ ntropy_ph │
│         ┆           ┆ i64        ┆ i32       ┆   ┆ 4         ┆ ---       ┆ 4         ┆ ase…      │
│         ┆           ┆            ┆           ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---       │
│         ┆           ┆            ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ f64       │
╞═════════╪═══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0       ┆ 351       ┆ 118        ┆ 2020      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1       ┆ 312       ┆ 141        ┆ 2020      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1       ┆ 345       ┆ 126        ┆ 2020      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1       ┆ 570       ┆ 121        ┆ 2020      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 2       ┆ 714       ┆ 193        ┆ 2020      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ …       ┆ …         ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 1176016 ┆ 124       ┆ 491        ┆ 2020      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1176016 ┆ 674       ┆ 103        ┆ 2019      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1176017 ┆ 676       ┆ 97         ┆ 2019      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1176017 ┆ 848       ┆ 165        ┆ 2020      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 1176018 ┆ 848       ┆ 48         ┆ 2019      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
└─────────┴───────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
from sklearn.model_selection import train_test_split
import pandas as pd

pandas_df = df.to_pandas()

train_df, temp_df = train_test_split(
    pandas_df,
    test_size=0.2,
    stratify=pandas_df['label_3'],
    random_state=42
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.5,
    stratify=temp_df['label_3'],
    random_state=42
)

print(f"Train set shape: {train_df.shape}")
print(f"Validation set shape: {val_df.shape}")
print(f"Test set shape: {test_df.shape}")

Train set shape: (1859619, 182)
Validation set shape: (232452, 182)
Test set shape: (232453, 182)

In [ ]:
column = val_df.columns

for i in column:
    print(i)

user_id
course_id
course_duration
start_year
start_month
start_day
enrollment_to_end
label_3
gender
num_course_order
avg_interval_enroll_time
max_interval_enroll_time
min_interval_enroll_time
first_enroll_year
last_enroll_year
most_enroll_month
enroll_ratio
name
video_counts
ex_counts
school_name
about_len
school_about_len
teacher_about_len
num_teachers
user_counts
ex_p1_average_attempts_1
ex_p1_average_ratio_1
ex_p1_average_exercise_time_1
ex_p1_average_time_between_submissions_1
ex_p1_average_enroll_to_first_submit_days_1
ex_p1_average_enroll_to_last_submit_days_1
ex_p1_exercise_completion_ratio_1
vid_p1_segment_duration_seconds_1
vid_p1_avg_segment_duration_1
vid_p1_avg_real_watch_time_1
vid_p1_segment_count_1
vid_p1_avg_playback_speed_1
vid_p1_avg_day_of_week_1
vid_p1_most_common_hour_1
vid_p1_most_common_day_1
vid_p1_unique_video_count_1
vid_p1_avg_segment_count_per_video_1
vid_p1_var_playback_speed_1
vid_p1_fast_forward_ratio_1
vid_p1_session_duration_std_1
cmt_p1_time_bin_phase1
cmt_p1_entropy_time_comment_phase1
cmt_p1_total_words_phase1
cmt_p1_total_negative_phase1
cmt_p1_total_neutral_phase1
cmt_p1_total_positive_phase1
cmt_p1_total_comments_phase1
cmt_p1_avg_comment_length_phase1
cmt_p1_std_comment_length_phase1
cmt_p1_max_comment_length_phase1
cmt_p1_text_diversity_phase1
cmt_p1_comment_days_active_phase1
cmt_p1_entropy_time_mean_phase1
cmt_p1_most_common_time_bin_phase1
cmt_p1_time_entropy_var_phase1
cmt_p1_positive_ratio_phase1
cmt_p1_neutral_ratio_phase1
cmt_p1_negative_ratio_phase1
cmt_p1_sentiment_entropy_phase1
ex_p2_average_attempts_2
ex_p2_average_ratio_2
ex_p2_average_exercise_time_2
ex_p2_average_time_between_submissions_2
ex_p2_average_enroll_to_first_submit_days_2
ex_p2_average_enroll_to_last_submit_days_2
ex_p2_exercise_completion_ratio_2
vid_p2_segment_duration_seconds_2
vid_p2_avg_segment_duration_2
vid_p2_avg_real_watch_time_2
vid_p2_segment_count_2
vid_p2_avg_playback_speed_2
vid_p2_avg_day_of_week_2
vid_p2_most_common_hour_2
vid_p2_most_common_day_2
vid_p2_unique_video_count_2
vid_p2_avg_segment_count_per_video_2
vid_p2_var_playback_speed_2
vid_p2_fast_forward_ratio_2
vid_p2_session_duration_std_2
cmt_p2_time_bin_phase2
cmt_p2_entropy_time_comment_phase2
cmt_p2_total_words_phase2
cmt_p2_total_negative_phase2
cmt_p2_total_neutral_phase2
cmt_p2_total_positive_phase2
cmt_p2_total_comments_phase2
cmt_p2_avg_comment_length_phase2
cmt_p2_std_comment_length_phase2
cmt_p2_max_comment_length_phase2
cmt_p2_text_diversity_phase2
cmt_p2_comment_days_active_phase2
cmt_p2_entropy_time_mean_phase2
cmt_p2_most_common_time_bin_phase2
cmt_p2_time_entropy_var_phase2
cmt_p2_positive_ratio_phase2
cmt_p2_neutral_ratio_phase2
cmt_p2_negative_ratio_phase2
cmt_p2_sentiment_entropy_phase2
ex_p3_average_attempts_3
ex_p3_average_ratio_3
ex_p3_average_exercise_time_3
ex_p3_average_time_between_submissions_3
ex_p3_average_enroll_to_first_submit_days_3
ex_p3_average_enroll_to_last_submit_days_3
ex_p3_exercise_completion_ratio_3
vid_p3_segment_duration_seconds_3
vid_p3_avg_segment_duration_3
vid_p3_avg_real_watch_time_3
vid_p3_segment_count_3
vid_p3_avg_playback_speed_3
vid_p3_avg_day_of_week_3
vid_p3_most_common_hour_3
vid_p3_most_common_day_3
vid_p3_unique_video_count_3
vid_p3_avg_segment_count_per_video_3
vid_p3_var_playback_speed_3
vid_p3_fast_forward_ratio_3
vid_p3_session_duration_std_3
cmt_p3_time_bin_phase3
cmt_p3_entropy_time_comment_phase3
cmt_p3_total_words_phase3
cmt_p3_total_negative_phase3
cmt_p3_total_neutral_phase3
cmt_p3_total_positive_phase3
cmt_p3_total_comments_phase3
cmt_p3_avg_comment_length_phase3
cmt_p3_std_comment_length_phase3
cmt_p3_max_comment_length_phase3
cmt_p3_text_diversity_phase3
cmt_p3_comment_days_active_phase3
cmt_p3_entropy_time_mean_phase3
cmt_p3_most_common_time_bin_phase3
cmt_p3_time_entropy_var_phase3
cmt_p3_positive_ratio_phase3
cmt_p3_neutral_ratio_phase3
cmt_p3_negative_ratio_phase3
cmt_p3_sentiment_entropy_phase3
ex_p4_average_attempts_4
ex_p4_average_ratio_4
ex_p4_average_exercise_time_4
ex_p4_average_time_between_submissions_4
ex_p4_average_enroll_to_first_submit_days_4
ex_p4_average_enroll_to_last_submit_days_4
ex_p4_exercise_completion_ratio_4
vid_p4_segment_duration_seconds_4
vid_p4_avg_segment_duration_4
vid_p4_avg_real_watch_time_4
vid_p4_segment_count_4
vid_p4_avg_playback_speed_4
vid_p4_avg_day_of_week_4
vid_p4_most_common_hour_4
vid_p4_most_common_day_4
vid_p4_unique_video_count_4
vid_p4_avg_segment_count_per_video_4
vid_p4_var_playback_speed_4
vid_p4_fast_forward_ratio_4
vid_p4_session_duration_std_4
cmt_p4_time_bin_phase4
cmt_p4_entropy_time_comment_phase4
cmt_p4_total_words_phase4
cmt_p4_total_negative_phase4
cmt_p4_total_neutral_phase4
cmt_p4_total_positive_phase4
cmt_p4_total_comments_phase4
cmt_p4_avg_comment_length_phase4
cmt_p4_std_comment_length_phase4
cmt_p4_max_comment_length_phase4
cmt_p4_text_diversity_phase4
cmt_p4_comment_days_active_phase4
cmt_p4_entropy_time_mean_phase4
cmt_p4_most_common_time_bin_phase4
cmt_p4_time_entropy_var_phase4
cmt_p4_positive_ratio_phase4
cmt_p4_neutral_ratio_phase4
cmt_p4_negative_ratio_phase4
cmt_p4_sentiment_entropy_phase4

In [ ]:
import pandas as pd

phase_end_columns = {
    'p1': 'cmt_p1_sentiment_entropy_phase1',
    'p2': 'cmt_p2_sentiment_entropy_phase2',
    'p3': 'cmt_p3_sentiment_entropy_phase3',
    'p4': 'cmt_p4_sentiment_entropy_phase4'
}

# Get the full list of columns from the validation DataFrame
all_columns = val_df.columns.tolist()

# Dictionaries to store the phase-specific DataFrames
val_dfs_by_phase = {}
test_dfs_by_phase = {}

print("Creating phase-specific DataFrames and zeroing out subsequent columns...")

for phase_name, end_col in phase_end_columns.items():
    if end_col in all_columns:
        # Find the index of the end column for the current phase
        end_col_idx = all_columns.index(end_col)

        # Get the names of columns that come *after* the end_col for this phase
        # These are the columns that should be zeroed out
        cols_to_zero_out = all_columns[end_col_idx + 1:]

        # Create a copy of the *entire* original DataFrame for each phase
        # and then set the 'future' columns to 0
        current_val_df_phase = val_df.copy()
        current_test_df_phase = test_df.copy()

        # Set the columns to zero
        for col in cols_to_zero_out:
            current_val_df_phase[col] = 0.0 # Use float to be consistent with existing numerical data
            current_test_df_phase[col] = 0.0

        val_dfs_by_phase[phase_name] = current_val_df_phase
        test_dfs_by_phase[phase_name] = current_test_df_phase

        print(f"  - {phase_name.upper()} Validation DataFrame shape: {val_dfs_by_phase[phase_name].shape}")
        print(f"  - {phase_name.upper()} Test DataFrame shape: {test_dfs_by_phase[phase_name].shape}")
    else:
        print(f"Warning: End column '{end_col}' for {phase_name.upper()} not found. Skipping phase.")

print("\nExample: Head of P1 Validation DataFrame (showing zeroed columns):")
display(val_dfs_by_phase['p1'].head())

Creating phase-specific DataFrames and zeroing out subsequent columns...
  - P1 Validation DataFrame shape: (232452, 182)
  - P1 Test DataFrame shape: (232453, 182)
  - P2 Validation DataFrame shape: (232452, 182)
  - P2 Test DataFrame shape: (232453, 182)
  - P3 Validation DataFrame shape: (232452, 182)
  - P3 Test DataFrame shape: (232453, 182)
  - P4 Validation DataFrame shape: (232452, 182)
  - P4 Test DataFrame shape: (232453, 182)

Example: Head of P1 Validation DataFrame (showing zeroed columns):

,user_id,course_id,course_duration,start_year,start_month,start_day,enrollment_to_end,label_3,gender,num_course_order,...,cmt_p4_max_comment_length_phase4,cmt_p4_text_diversity_phase4,cmt_p4_comment_days_active_phase4,cmt_p4_entropy_time_mean_phase4,cmt_p4_most_common_time_bin_phase4,cmt_p4_time_entropy_var_phase4,cmt_p4_positive_ratio_phase4,cmt_p4_neutral_ratio_phase4,cmt_p4_negative_ratio_phase4,cmt_p4_sentiment_entropy_phase4
1222152,353303,714,193,2020,1,20,163,2,1.0,11,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
185650,108795,363,119,2020,9,3,70,2,0.0,62,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2271794,1137107,57,122,2020,3,31,87,2,2.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
688008,153837,45,126,2020,3,26,37,2,0.0,54,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1737160,713106,833,93,2020,4,13,91,2,2.0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
display(val_dfs_by_phase['p4'].head())

,user_id,course_id,course_duration,start_year,start_month,start_day,enrollment_to_end,label_3,gender,num_course_order,...,cmt_p4_max_comment_length_phase4,cmt_p4_text_diversity_phase4,cmt_p4_comment_days_active_phase4,cmt_p4_entropy_time_mean_phase4,cmt_p4_most_common_time_bin_phase4,cmt_p4_time_entropy_var_phase4,cmt_p4_positive_ratio_phase4,cmt_p4_neutral_ratio_phase4,cmt_p4_negative_ratio_phase4,cmt_p4_sentiment_entropy_phase4
1222152,353303,714,193,2020,1,20,163,2,1.0,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185650,108795,363,119,2020,9,3,70,2,0.0,62,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2271794,1137107,57,122,2020,3,31,87,2,2.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
688008,153837,45,126,2020,3,26,37,2,0.0,54,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1737160,713106,833,93,2020,4,13,91,2,2.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import os

# Define the output directory
output_dir = 'data_output'

# Create the output directory if it doesn't exist
os.makedirs(output_dir, exist_ok=True)

print(f"Saving DataFrames to CSV files in '{output_dir}'...")

# Save the training DataFrame
train_df_path = os.path.join(output_dir, 'train.csv')
train_df.to_csv(train_df_path, index=False)
print(f"  - Saved train_df to {train_df_path}")

# Save validation phase DataFrames
for phase_name, df_phase in val_dfs_by_phase.items():
    val_path = os.path.join(output_dir, f'val_{phase_name}.csv')
    df_phase.to_csv(val_path, index=False)
    print(f"  - Saved validation {phase_name.upper()} DataFrame to {val_path}")

# Save test phase DataFrames
for phase_name, df_phase in test_dfs_by_phase.items():
    test_path = os.path.join(output_dir, f'test_{phase_name}.csv')
    df_phase.to_csv(test_path, index=False)
    print(f"  - Saved test {phase_name.upper()} DataFrame to {test_path}")

print("All specified DataFrames have been saved.")

Saving DataFrames to CSV files in 'data_output'...
  - Saved train_df to data_output/train.csv
  - Saved validation P1 DataFrame to data_output/val_p1.csv
  - Saved validation P2 DataFrame to data_output/val_p2.csv
  - Saved validation P3 DataFrame to data_output/val_p3.csv
  - Saved validation P4 DataFrame to data_output/val_p4.csv
  - Saved test P1 DataFrame to data_output/test_p1.csv
  - Saved test P2 DataFrame to data_output/test_p2.csv
  - Saved test P3 DataFrame to data_output/test_p3.csv
  - Saved test P4 DataFrame to data_output/test_p4.csv
All specified DataFrames have been saved.

In [ ]:
import shutil
import os

# Define source and destination paths
source_folder = 'data_output'
destination_folder = '/content/drive/MyDrive/DS317 (1)/data_output_3'

# Check if the source folder exists
if not os.path.exists(source_folder):
    print(f"Error: Source folder '{source_folder}' does not exist.")
else:
    # Check if the destination path exists (the parent directory)
    if not os.path.exists(os.path.dirname(destination_folder)):
        print(f"Error: Destination parent directory '{os.path.dirname(destination_folder)}' does not exist. Please check your Google Drive path.")
    else:
        try:
            # Move the folder
            shutil.move(source_folder, destination_folder)
            print(f"Folder '{source_folder}' successfully moved to '{destination_folder}'.")
        except Exception as e:
            print(f"An error occurred while moving the folder: {e}")

Folder 'data_output' successfully moved to '/content/drive/MyDrive/DS317 (1)/data_output_3'.