In [ ]:
!pip install pyarrow

Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)

In [ ]:

# import thư viện
import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
import matplotlib.font_manager as fm

# Load data

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Load file clean_user_video.csv
path_user_video = "/content/drive/MyDrive/MOOCCubeX/Dataset/Data_cleaned/user_video/clean_user_video.csv"
df_user_video = pd.read_csv(path_user_video)
df_user_video.head()

,user_id,video_id,start_point,end_point,playback_speed,timestamp,datetime_utc,hour_of_day,day_of_week,speed_category,segment_duration_seconds
0,U_112,V_1395633,130.0,190.00,1.00,1588431144,2020-05-02T06:52:24.000000+0000,6,6,normal,60.00
1,U_112,V_1395633,220.0,250.00,1.00,1588431234,2020-05-02T06:53:54.000000+0000,6,6,normal,30.00
2,U_112,V_1395633,478.8,508.80,1.00,1588437359,2020-05-02T08:35:59.000000+0000,8,6,normal,30.00
3,U_112,V_1395633,655.1,692.55,1.25,1588437514,2020-05-02T08:38:34.000000+0000,8,6,fast,37.45
4,U_112,V_1395635,135.0,170.00,1.00,1588438045,2020-05-02T08:47:25.000000+0000,8,6,normal,35.00

In [ ]:
df_user_video.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25748664 entries, 0 to 25748663
Data columns (total 11 columns):
 #   Column                    Dtype
---  ------                    -----
 0   user_id                   object
 1   video_id                  object
 2   start_point               float64
 3   end_point                 float64
 4   playback_speed            float64
 5   timestamp                 int64
 6   datetime_utc              object
 7   hour_of_day               int64
 8   day_of_week               int64
 9   speed_category            object
 10  segment_duration_seconds  float64
dtypes: float64(4), int64(3), object(4)
memory usage: 2.1+ GB

In [ ]:
#Load file user_course_use_labeling.qarquet
path_user_info = "/content/drive/MyDrive/MOOCCubeX/Dataset/Data_cleaned/Label_3_and_5_classes(have_course_info).csv"
df_user_info = pd.read_csv(path_user_info)
df_user_info.head()

,course_id,start_date,end_date,assignment,video,exam,course_duration,user_id,enroll_time,enrollment_to_end,...,average_correct_ratio_exam,amount_exercise_each_assignment,total_correct_ratio_assignment,average_correct_ratio_assignment,watched_videos,video_counts,watch_percent,score,label_3,label_5
0,C_2033958,2020-09-04,2020-12-31,40.0,30.0,30.0,118,U_10000,2020-10-27 09:07:30,64,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,E,E
1,C_1925903,2020-08-12,2020-12-31,30.0,30.0,40.0,141,U_1000129,2020-09-06 14:37:17,115,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,E,E
2,C_1992970,2020-08-27,2020-12-31,30.0,30.0,40.0,126,U_1000129,2020-09-06 14:45:37,115,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,E,E
3,C_680884,2020-09-01,2020-12-31,80.0,20.0,0.0,121,U_1000129,2020-10-16 10:41:09,75,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,E,E
4,C_697791,2020-01-20,2020-07-31,80.0,20.0,0.0,193,U_1000342,2020-02-28 10:27:22,153,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,E,E

In [ ]:
df_user_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2324544 entries, 0 to 2324543
Data columns (total 22 columns):
 #   Column                            Dtype
---  ------                            -----
 0   course_id                         object
 1   start_date                        object
 2   end_date                          object
 3   assignment                        float64
 4   video                             float64
 5   exam                              float64
 6   course_duration                   int64
 7   user_id                           object
 8   enroll_time                       object
 9   enrollment_to_end                 int64
 10  amount_exercise_each_exam         float64
 11  total_correct_ratio_exam          float64
 12  average_correct_ratio_exam        float64
 13  amount_exercise_each_assignment   float64
 14  total_correct_ratio_assignment    float64
 15  average_correct_ratio_assignment  float64
 16  watched_videos                    float64
 17  video_counts                      float64
 18  watch_percent                     float64
 19  score                             float64
 20  label_3                           object
 21  label_5                           object
dtypes: float64(13), int64(2), object(7)
memory usage: 390.2+ MB

In [ ]:
#Load file user_course_use_labeling.qarquet
path_resource = "/content/drive/MyDrive/MOOCCubeX/Dataset/resource_video_course.parquet"
df_resource = pd.read_parquet(path_resource)
df_resource.head()

,id,titles_chapter,title_video,chapter,video_id,video_counts
0,C_1017355,"[Unit 1 Introduction to Chinese Medicine, Unit...","[1.1 Brief History of Chinese Medicine, 1.2\t...","[0, 0.1, 1, 1.1, 1.1.1, 1.2.1, 2, 2.1, 3, 3.1,...","[V_1617852, V_1617854, V_1736570, V_1736573, V...",19
1,C_1017419,"[课程简介, 第一讲 智慧政府：智慧金融, 第一讲 智慧政府：智慧金融, 第二讲 智慧政府：...","[课程宣传视频, 一、什么是智慧金融, 二、政府如何建立完善智慧金融征信体系？, 一、智慧政...","[1.2, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2, 5.1, 5.2, ...","[V_1618247, V_1618249, V_1618250, V_1618252, V...",17
2,C_1025064,"[第1章 思想政治教育与思想政治教育学述要, 第1章 思想政治教育与思想政治教育学述...","[1.1 思想政治教育的概念, 1.2思想政治教育的内涵与外延, 1.3 思想政治教育学的研...","[0, 0.1, 0.2, 0.3, 0.3.1, 0.3.2, 0.4, 0.5, 1, ...","[V_1622546, V_1622547, V_1622548, V_1622549, V...",89
3,C_1025076,"[第一章 轮滑运动规则与赏析, 第一章 轮滑运动规则与赏析, 第一章 轮滑运动规则与赏析, ...","[第1节 轮滑运动竞赛规则简介 , 第1节 轮滑运动竞赛规则简介 , 第1节 轮滑运动竞赛规...","[0, 0.1, 0.2, 0.3, 0.2, 0.2.1, 0.2.2, 0.2.3, 0...","[V_1622858, V_1622859, V_1622860, V_1622861, V...",43
4,C_1025079,"[第一周, 第一周, 第一周, 第一周, 第二周, 第二周, 第二周, 第二周, 第三周, ...","[1.1何为缠丝功, 1.2如何练习缠丝功, 2.1揉手--旋指, 2.1揉手--转腕, 2...","[1.1.1, 1.2.1, 1.3.1, 1.4.1, 2.1.1, 2.2.1, 2.3...","[V_1622989, V_1622990, V_1622991, V_1622992, V...",34

In [ ]:
df_resource_new = pd.DataFrame()
df_resource_new[['course_id', 'video_id']] = df_resource[['id', 'video_id']]
df_resource_new.head()

   course_id                                           video_id
0  C_1017355  [V_1617852, V_1617854, V_1736570, V_1736573, V...
1  C_1017419  [V_1618247, V_1618249, V_1618250, V_1618252, V...
2  C_1025064  [V_1622546, V_1622547, V_1622548, V_1622549, V...
3  C_1025076  [V_1622858, V_1622859, V_1622860, V_1622861, V...
4  C_1025079  [V_1622989, V_1622990, V_1622991, V_1622992, V...

In [ ]:
df_resource_new.shape

(3770, 2)

In [ ]:
df_exploded = df_resource_new.explode('video_id')

# reset lại index
df_exploded = df_exploded.reset_index(drop=True)

# xem kết quả
df_exploded.head()

   course_id   video_id
0  C_1017355  V_1617852
1  C_1017355  V_1617854
2  C_1017355  V_1736570
3  C_1017355  V_1736573
4  C_1017355  V_1617856

In [ ]:
# Merge df_exploded với df_user_video
df_user_video_course = df_user_video.merge(
    df_exploded,
    on=["video_id"],
    how="inner"
)
print("Trước khi merge:", len(df_user_video))
print("Sau khi merge:", len(df_user_video_course))

Trước khi merge: 25748664
Sau khi merge: 524189

In [ ]:
df_user_video_course.head()

,user_id,video_id,start_point,end_point,playback_speed,timestamp,datetime_utc,hour_of_day,day_of_week,speed_category,segment_duration_seconds,course_id
0,U_172,V_6432959,4552.1,4556.8,1.0,1598192594,2020-08-23T06:23:14.000000+0000,6,7,normal,4.7,C_1924175
1,U_1368,V_6392554,105.6,130.4,1.0,1597654983,2020-08-17T01:03:03.000000+0000,1,1,normal,24.8,C_1912735
2,U_1819,V_7406237,4.9,79.9,1.0,1600788116,2020-09-22T07:21:56.000000+0000,7,2,normal,75.0,C_2203228
3,U_1819,V_7406237,340.0,360.0,1.0,1600788215,2020-09-22T07:23:35.000000+0000,7,2,normal,20.0,C_2203228
4,U_1819,V_7406238,4.9,45.0,1.0,1600788242,2020-09-22T07:24:02.000000+0000,7,2,normal,40.1,C_2203228

# Merge file

In [ ]:
# Merge df_user_video_course với df_user_info
merged_df = df_user_info.merge(
    df_user_video_course,
    on=["user_id", "course_id"],
    how="inner"
)

print("Trước khi merge:", len(df_user_info))
print("Sau khi merge:", len(merged_df))

# # Lưu merged_df ra file csv
# merged_file = "merged_df.csv"
# merged_df.to_csv(merged_file, index=False)
# print(f"Đã lưu merged_df ra file: {merged_file}") #429665

display(merged_df.head())

Trước khi merge: 2324544
Sau khi merge: 260197

,course_id,start_date,end_date,assignment,video,exam,course_duration,user_id,enroll_time,enrollment_to_end,...,video_id,start_point,end_point,playback_speed,timestamp,datetime_utc,hour_of_day,day_of_week,speed_category,segment_duration_seconds
0,C_2199449,2020-09-17,2021-01-31,50.0,30.0,20.0,136,U_1000454,2020-10-12 13:24:59,110,...,V_7396061,16.6,466.681,1.0,1602669376,2020-10-14T01:56:16.000000+0000,1,3,normal,450.081
1,C_1756056,2020-04-12,2021-06-30,70.0,30.0,0.0,444,U_1002784,2020-10-13 17:13:34,259,...,V_4411676,34.9,385.100,1.0,1604120790,2020-10-30T21:06:30.000000+0000,21,5,normal,350.200
2,C_1756056,2020-04-12,2021-06-30,70.0,30.0,0.0,444,U_1002784,2020-10-13 17:13:34,259,...,V_4411678,4.9,290.300,1.0,1604121149,2020-10-30T21:12:29.000000+0000,21,5,normal,285.400
3,C_1756056,2020-04-12,2021-06-30,70.0,30.0,0.0,444,U_1002784,2020-10-13 17:13:34,259,...,V_4411680,7.6,557.600,1.0,1604121505,2020-10-30T21:18:25.000000+0000,21,5,normal,550.000
4,C_676642,2020-02-06,2020-07-31,40.0,30.0,30.0,176,U_10033817,2020-06-09 08:54:03,51,...,V_1642603,4.0,14.000,1.0,1598321411,2020-08-24T18:10:11.000000+0000,18,1,normal,10.000

In [ ]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260197 entries, 0 to 260196
Data columns (total 32 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   course_id                         260197 non-null  object
 1   start_date                        260197 non-null  object
 2   end_date                          260197 non-null  object
 3   assignment                        260197 non-null  float64
 4   video                             260197 non-null  float64
 5   exam                              260197 non-null  float64
 6   course_duration                   260197 non-null  int64
 7   user_id                           260197 non-null  object
 8   enroll_time                       260197 non-null  object
 9   enrollment_to_end                 260197 non-null  int64
 10  amount_exercise_each_exam         260197 non-null  float64
 11  total_correct_ratio_exam          260197 non-null  float64
 12  average_correct_ratio_exam        260197 non-null  float64
 13  amount_exercise_each_assignment   260197 non-null  float64
 14  total_correct_ratio_assignment    260197 non-null  float64
 15  average_correct_ratio_assignment  260197 non-null  float64
 16  watched_videos                    260197 non-null  float64
 17  video_counts                      260197 non-null  float64
 18  watch_percent                     260197 non-null  float64
 19  score                             260197 non-null  float64
 20  label_3                           260197 non-null  object
 21  label_5                           260197 non-null  object
 22  video_id                          260197 non-null  object
 23  start_point                       260197 non-null  float64
 24  end_point                         260197 non-null  float64
 25  playback_speed                    260197 non-null  float64
 26  timestamp                         260197 non-null  int64
 27  datetime_utc                      260197 non-null  object
 28  hour_of_day                       260197 non-null  int64
 29  day_of_week                       260197 non-null  int64
 30  speed_category                    260197 non-null  object
 31  segment_duration_seconds          260197 non-null  float64
dtypes: float64(17), int64(5), object(10)
memory usage: 63.5+ MB

# Chia dữ liệu thành 4 phase

## Thực hiện tính toán về thời gian

In [ ]:
df_temp = pd.DataFrame()
df_temp['enroll_time'] = pd.to_datetime(merged_df['enroll_time'])
df_temp['datetime_utc'] = pd.to_datetime(merged_df['datetime_utc']).dt.tz_localize(None)

df_temp['days_since_enroll'] = (df_temp['datetime_utc'] - df_temp['enroll_time']).abs().dt.days
df_temp.head()

          enroll_time        datetime_utc  days_since_enroll
0 2020-10-12 13:24:59 2020-10-14 01:56:16                  1
1 2020-10-13 17:13:34 2020-10-30 21:06:30                 17
2 2020-10-13 17:13:34 2020-10-30 21:12:29                 17
3 2020-10-13 17:13:34 2020-10-30 21:18:25                 17
4 2020-06-09 08:54:03 2020-08-24 18:10:11                 76

In [ ]:
merged_df['days_since_enroll'] = df_temp['days_since_enroll']
merged_df.head()

,course_id,start_date,end_date,assignment,video,exam,course_duration,user_id,enroll_time,enrollment_to_end,...,start_point,end_point,playback_speed,timestamp,datetime_utc,hour_of_day,day_of_week,speed_category,segment_duration_seconds,days_since_enroll
0,C_2199449,2020-09-17,2021-01-31,50.0,30.0,20.0,136,U_1000454,2020-10-12 13:24:59,110,...,16.6,466.681,1.0,1602669376,2020-10-14T01:56:16.000000+0000,1,3,normal,450.081,1
1,C_1756056,2020-04-12,2021-06-30,70.0,30.0,0.0,444,U_1002784,2020-10-13 17:13:34,259,...,34.9,385.100,1.0,1604120790,2020-10-30T21:06:30.000000+0000,21,5,normal,350.200,17
2,C_1756056,2020-04-12,2021-06-30,70.0,30.0,0.0,444,U_1002784,2020-10-13 17:13:34,259,...,4.9,290.300,1.0,1604121149,2020-10-30T21:12:29.000000+0000,21,5,normal,285.400,17
3,C_1756056,2020-04-12,2021-06-30,70.0,30.0,0.0,444,U_1002784,2020-10-13 17:13:34,259,...,7.6,557.600,1.0,1604121505,2020-10-30T21:18:25.000000+0000,21,5,normal,550.000,17
4,C_676642,2020-02-06,2020-07-31,40.0,30.0,30.0,176,U_10033817,2020-06-09 08:54:03,51,...,4.0,14.000,1.0,1598321411,2020-08-24T18:10:11.000000+0000,18,1,normal,10.000,76

In [ ]:
merged_df.shape

(260197, 33)

In [ ]:
# # Lưu lại file
# merged_file = "merged_df.csv"
# merged_df.to_csv(merged_file, index=False)
# print(f"Đã lưu merged_df ra file: {merged_file}")

## Thực hiện gán phase

In [ ]:
df = merged_df.copy()
print(f"Số dòng ban đầu: {len(df)}")
# Hàm gán phase
def assign_phase(row):
    days = row['days_since_enroll']
    course_duration = row['enrollment_to_end']
    if days <= 0.25 * course_duration:
        return 'Phase_1'
    elif days <= 0.50 * course_duration:
        return 'Phase_2'
    elif days <= 0.75 * course_duration:
        return 'Phase_3'
    elif days <= 0.9 * course_duration:
        return 'Phase_4'
    else:
        return None

# Gán giá trị phase cho từng dòng dựa vào số ngày kể từ khi ghi danh và thời lượng khóa học
df['phase'] = df.apply(assign_phase, axis=1)

df = df[df['phase'].notna()]
print(f"Số dòng sau khi gán phase: {len(df)}")

print("\nPhân bố phase:")
print(df['phase'].value_counts().sort_index())  # Đếm số dòng theo từng phase

Số dòng ban đầu: 260197
Số dòng sau khi gán phase: 217122

Phân bố phase:
phase
Phase_1    175555
Phase_2     25554
Phase_3      8216
Phase_4      7797
Name: count, dtype: int64

In [ ]:
df.columns

Index(['course_id', 'start_date', 'end_date', 'assignment', 'video', 'exam',
       'course_duration', 'user_id', 'enroll_time', 'enrollment_to_end',
       'amount_exercise_each_exam', 'total_correct_ratio_exam',
       'average_correct_ratio_exam', 'amount_exercise_each_assignment',
       'total_correct_ratio_assignment', 'average_correct_ratio_assignment',
       'watched_videos', 'video_counts', 'watch_percent', 'score', 'label_3',
       'label_5', 'video_id', 'start_point', 'end_point', 'playback_speed',
       'timestamp', 'datetime_utc', 'hour_of_day', 'day_of_week',
       'speed_category', 'segment_duration_seconds', 'days_since_enroll',
       'phase'],
      dtype='object')

## Kiểm tra trùng lắp và groupby

In [ ]:
import pandas as pd

# ===== Hàm tính tổng thời gian xem thực tế (loại trừ chồng lấn) =====
def total_watch_time(start_point, end_point):
    intervals = sorted(zip(start_point, end_point), key=lambda x: x[0])
    merged = []
    for start, end in intervals:
        if not merged or start > merged[-1][1]:
            merged.append([start, end])
        else:
            merged[-1][1] = max(merged[-1][1], end)
    total = sum(e - s for s, e in merged)
    return total


# ===== Hàm tính các đặc trưng xem video =====
def compute_features(group):
    avg_segment_duration = (group['end_point'] - group['start_point']).mean()
    real_watch_time = total_watch_time(group['start_point'].tolist(), group['end_point'].tolist())
    avg_real_watch_time = real_watch_time / len(group)
    segment_count = len(group)
    avg_playback_speed = group['playback_speed'].mean()
    avg_day_of_week = round(group['day_of_week'].mean())

    most_common_hour = (
        group['hour_of_day'].value_counts().idxmax()
        if not group['hour_of_day'].isnull().all()
        else None
    )
    most_common_day = (
        group['day_of_week'].value_counts().idxmax()
        if not group['day_of_week'].isnull().all()
        else None
    )

    unique_video_count = group['video_id'].nunique()
    avg_segment_count_per_video = segment_count / unique_video_count if unique_video_count > 0 else 0
    var_playback_speed = group['playback_speed'].var(ddof=0)
    fast_forward_ratio = (group['playback_speed'] > 1.0).mean()

    if 'segment_duration_seconds' in group.columns:
        session_duration_std = group['segment_duration_seconds'].std(ddof=0)
    else:
        session_duration_std = (group['end_point'] - group['start_point']).std(ddof=0)

    return pd.Series({
        'avg_segment_duration': avg_segment_duration,
        'avg_real_watch_time': avg_real_watch_time,
        'segment_count': segment_count,
        'avg_playback_speed': avg_playback_speed,
        'avg_day_of_week': avg_day_of_week,
        'most_common_hour': most_common_hour,
        'most_common_day': most_common_day,
        'unique_video_count': unique_video_count,
        'avg_segment_count_per_video': avg_segment_count_per_video,
        'var_playback_speed': var_playback_speed,
        'fast_forward_ratio': fast_forward_ratio,
        'session_duration_std': session_duration_std
    })


# ===== Pipeline tổng hợp dữ liệu theo phase =====
phases = ['Phase_1', 'Phase_2', 'Phase_3', 'Phase_4']
group_cols = ['user_id', 'course_id', 'enroll_time']

agg_results = {}

for i, phase in enumerate(phases, start=1):
    print(f"\n=== {phase} ===")

    # Lọc dữ liệu theo phase
    df_phase = df[df['phase'] == phase].copy()

    # Bỏ cột không cần thiết
    drop_cols = ['days_since_enroll']
    df_phase = df_phase.drop(columns=drop_cols, errors='ignore')

    # Kiểm tra trùng lặp
    num_dups_before = df_phase.duplicated(subset=group_cols, keep=False).sum()
    print(f"Trước khi gộp: {num_dups_before} bản ghi trùng dựa trên {group_cols}.")

    if num_dups_before == 0:
        print("Không có bản ghi trùng, giữ nguyên dữ liệu.")
        df_phase['phase'] = i
        df_phase['num_videos_watched'] = 1
        agg_results[i] = df_phase.copy()

    else:
        print("Có trùng, tiến hành groupby và tính đặc trưng hành vi xem video...")

        # Tính đặc trưng chi tiết
        feature_df = df_phase.groupby(group_cols).apply(compute_features).reset_index()

        # Gộp thêm các đặc trưng numeric khác (ví dụ điểm, tỉ lệ, v.v.)
        numeric_cols = df_phase.select_dtypes(include=['int64', 'float64']).columns.tolist()
        numeric_cols = [c for c in numeric_cols if c not in ['phase', 'start_point', 'end_point']]

        sum_cols = ['segment_duration_seconds']
        mean_cols = [c for c in numeric_cols if c not in sum_cols]
        agg_dict = {col: 'mean' for col in mean_cols}
        for c in sum_cols:
            agg_dict[c] = 'sum'

        agg_numeric = (
            df_phase.groupby(group_cols, as_index=False)
            .agg(agg_dict)
            .sort_values(by=group_cols)
            .reset_index(drop=True)
        )

        # Đếm số video duy nhất
        video_count = (
            df_phase.groupby(group_cols)['video_id']
            .nunique()
            .reset_index(name='num_videos_watched')
        )

        # Gộp tất cả: numeric + feature + video_count
        agg_final = (
            agg_numeric
            .merge(feature_df, on=group_cols, how='left')
            .merge(video_count, on=group_cols, how='left')
        )

        agg_final['phase'] = i
        agg_results[i] = agg_final

print("\n✅ Hoàn tất gộp dữ liệu tất cả phase.")

=== Phase_1 ===
Trước khi gộp: 173066 bản ghi trùng dựa trên ['user_id', 'course_id', 'enroll_time'].
Có trùng, tiến hành groupby và tính đặc trưng hành vi xem video...

/tmp/ipython-input-3730654510.py:92: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  feature_df = df_phase.groupby(group_cols).apply(compute_features).reset_index()

=== Phase_2 ===
Trước khi gộp: 25037 bản ghi trùng dựa trên ['user_id', 'course_id', 'enroll_time'].
Có trùng, tiến hành groupby và tính đặc trưng hành vi xem video...

/tmp/ipython-input-3730654510.py:92: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  feature_df = df_phase.groupby(group_cols).apply(compute_features).reset_index()

=== Phase_3 ===
Trước khi gộp: 8156 bản ghi trùng dựa trên ['user_id', 'course_id', 'enroll_time'].
Có trùng, tiến hành groupby và tính đặc trưng hành vi xem video...

/tmp/ipython-input-3730654510.py:92: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  feature_df = df_phase.groupby(group_cols).apply(compute_features).reset_index()

=== Phase_4 ===
Trước khi gộp: 7770 bản ghi trùng dựa trên ['user_id', 'course_id', 'enroll_time'].
Có trùng, tiến hành groupby và tính đặc trưng hành vi xem video...

✅ Hoàn tất gộp dữ liệu tất cả phase.

/tmp/ipython-input-3730654510.py:92: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  feature_df = df_phase.groupby(group_cols).apply(compute_features).reset_index()

In [ ]:
# Kiểm tra dữ liệu sau groupby
for phase, agg_df in agg_results.items():
    num_dups_after = agg_df.duplicated(subset=group_cols, keep=False).sum()
    print(f"\n{phase}: Còn {num_dups_after} bản ghi trùng sau khi gộp.")

    if num_dups_after != 0:
        print("Vẫn còn trùng, cần kiểm tra logic groupby.")

1: Còn 0 bản ghi trùng sau khi gộp.

2: Còn 0 bản ghi trùng sau khi gộp.

3: Còn 0 bản ghi trùng sau khi gộp.

4: Còn 0 bản ghi trùng sau khi gộp.

In [ ]:
agg_results[1].shape

(12424, 37)

In [ ]:
cols_to_drop = [
    'enroll_time', 'Unnamed: 0', 'video', 'assignment', 'exam', 'amount_exercise_each_exam',
       'total_correct_ratio_exam', 'average_correct_ratio_exam',
       'amount_exercise_each_assignment', 'total_correct_ratio_assignment',
       'average_correct_ratio_assignment', 'watched_videos', 'video_counts',
       'watch_percent', 'score', 'course_duration', 'enrollment_to_end','playback_speed', 'timestamp',
    'hour_of_day', 'day_of_week','num_videos_watched'
]

for phase, agg_df in agg_results.items():
    agg_results[phase] = agg_df.drop(columns=cols_to_drop, errors='ignore')
    print(f"Columns in Phase {phase} after dropping: {agg_results[phase].columns.tolist()}")

print("\nFinished dropping columns from all phases.")

Columns in Phase 1 after dropping: ['user_id', 'course_id', 'segment_duration_seconds', 'avg_segment_duration', 'avg_real_watch_time', 'segment_count', 'avg_playback_speed', 'avg_day_of_week', 'most_common_hour', 'most_common_day', 'unique_video_count', 'avg_segment_count_per_video', 'var_playback_speed', 'fast_forward_ratio', 'session_duration_std', 'phase']
Columns in Phase 2 after dropping: ['user_id', 'course_id', 'segment_duration_seconds', 'avg_segment_duration', 'avg_real_watch_time', 'segment_count', 'avg_playback_speed', 'avg_day_of_week', 'most_common_hour', 'most_common_day', 'unique_video_count', 'avg_segment_count_per_video', 'var_playback_speed', 'fast_forward_ratio', 'session_duration_std', 'phase']
Columns in Phase 3 after dropping: ['user_id', 'course_id', 'segment_duration_seconds', 'avg_segment_duration', 'avg_real_watch_time', 'segment_count', 'avg_playback_speed', 'avg_day_of_week', 'most_common_hour', 'most_common_day', 'unique_video_count', 'avg_segment_count_per_video', 'var_playback_speed', 'fast_forward_ratio', 'session_duration_std', 'phase']
Columns in Phase 4 after dropping: ['user_id', 'course_id', 'segment_duration_seconds', 'avg_segment_duration', 'avg_real_watch_time', 'segment_count', 'avg_playback_speed', 'avg_day_of_week', 'most_common_hour', 'most_common_day', 'unique_video_count', 'avg_segment_count_per_video', 'var_playback_speed', 'fast_forward_ratio', 'session_duration_std', 'phase']

Finished dropping columns from all phases.

In [ ]:
for phase, agg_df in agg_results.items():
    # Rename columns by adding phase suffix, excluding 'user_id' and 'course_id'
    renamed_columns = {}
    for col in agg_df.columns:
        if col not in ['user_id', 'course_id']:
            renamed_columns[col] = f"{col}_{phase}"
        else:
            renamed_columns[col] = col  # Keep 'user_id' and 'course_id' as they are
    agg_results[phase] = agg_df.rename(columns=renamed_columns)

    print(f"Columns in Phase {phase} after renaming: {agg_results[phase].columns.tolist()}")

print("\nFinished renaming columns in all phases.")

Columns in Phase 1 after renaming: ['user_id', 'course_id', 'segment_duration_seconds_1', 'avg_segment_duration_1', 'avg_real_watch_time_1', 'segment_count_1', 'avg_playback_speed_1', 'avg_day_of_week_1', 'most_common_hour_1', 'most_common_day_1', 'unique_video_count_1', 'avg_segment_count_per_video_1', 'var_playback_speed_1', 'fast_forward_ratio_1', 'session_duration_std_1', 'phase_1']
Columns in Phase 2 after renaming: ['user_id', 'course_id', 'segment_duration_seconds_2', 'avg_segment_duration_2', 'avg_real_watch_time_2', 'segment_count_2', 'avg_playback_speed_2', 'avg_day_of_week_2', 'most_common_hour_2', 'most_common_day_2', 'unique_video_count_2', 'avg_segment_count_per_video_2', 'var_playback_speed_2', 'fast_forward_ratio_2', 'session_duration_std_2', 'phase_2']
Columns in Phase 3 after renaming: ['user_id', 'course_id', 'segment_duration_seconds_3', 'avg_segment_duration_3', 'avg_real_watch_time_3', 'segment_count_3', 'avg_playback_speed_3', 'avg_day_of_week_3', 'most_common_hour_3', 'most_common_day_3', 'unique_video_count_3', 'avg_segment_count_per_video_3', 'var_playback_speed_3', 'fast_forward_ratio_3', 'session_duration_std_3', 'phase_3']
Columns in Phase 4 after renaming: ['user_id', 'course_id', 'segment_duration_seconds_4', 'avg_segment_duration_4', 'avg_real_watch_time_4', 'segment_count_4', 'avg_playback_speed_4', 'avg_day_of_week_4', 'most_common_hour_4', 'most_common_day_4', 'unique_video_count_4', 'avg_segment_count_per_video_4', 'var_playback_speed_4', 'fast_forward_ratio_4', 'session_duration_std_4', 'phase_4']

Finished renaming columns in all phases.

In [ ]:
agg_results[4]

,user_id,course_id,segment_duration_seconds_4,avg_segment_duration_4,avg_real_watch_time_4,segment_count_4,avg_playback_speed_4,avg_day_of_week_4,most_common_hour_4,most_common_day_4,unique_video_count_4,avg_segment_count_per_video_4,var_playback_speed_4,fast_forward_ratio_4,session_duration_std_4,phase_4
0,U_10340035,C_2059299,1559.557117,91.738654,91.738654,17.0,1.941176,4.0,7.0,4.0,1.0,17.000000,0.055363,0.941176,53.279202,4
1,U_10340055,C_2059299,180.286005,30.047667,29.713501,6.0,1.000000,4.0,6.0,4.0,1.0,6.000000,0.000000,0.000000,18.497225,4
2,U_10340068,C_2059299,3108.100000,115.114815,56.670370,27.0,1.000000,5.0,18.0,5.0,19.0,1.421053,0.000000,0.000000,119.706053,4
3,U_10340072,C_2059299,2628.100000,14.600556,6.475000,180.0,1.861111,5.0,18.0,5.0,5.0,36.000000,0.119599,0.861111,34.799637,4
4,U_10340197,C_2059299,3789.800000,157.908333,64.887500,24.0,1.125000,5.0,17.0,5.0,7.0,3.428571,0.109375,0.125000,116.382276,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,U_8144973,C_2059299,1544.004080,12.062532,9.604266,128.0,1.000000,7.0,0.0,7.0,9.0,14.222222,0.000000,0.000000,42.442149,4
262,U_8511480,C_680992,1349.800000,134.980000,58.940000,10.0,1.000000,4.0,22.0,4.0,6.0,1.666667,0.000000,0.000000,107.804108,4
263,U_9529451,C_2059299,120.100000,60.050000,60.050000,2.0,1.000000,5.0,17.0,5.0,1.0,2.000000,0.000000,0.000000,4.950000,4
264,U_9863516,C_1797904,10.000000,10.000000,10.000000,1.0,1.000000,2.0,4.0,2.0,1.0,1.000000,0.000000,0.000000,0.000000,4
265,U_994092,C_1891064,25.010000,25.010000,25.010000,1.0,1.000000,6.0,16.0,6.0,1.0,1.000000,0.000000,0.000000,0.000000,4

## Lưu file

In [ ]:
# Lưu phase vào 4 file
for phase, agg_df in agg_results.items():
    # Drop the phase column before saving
    if f'phase_{phase}' in agg_df.columns:
      agg_df = agg_df.drop(columns=[f'phase_{phase}'])
    elif 'phase' in agg_df.columns: # Handle case where phase column was not renamed
      agg_df = agg_df.drop(columns=['phase'])

    filename = f"/content/drive/MyDrive/MOOCCubeX/Dataset/Data_cleaned/video_phase_{phase}.csv"
    agg_df.to_csv(filename, index=False)
    print(f"Đã lưu {filename}: {len(agg_df)} dòng, {len(agg_df.columns)} cột")

print("\nHoàn tất xử lý và lưu tất cả 4 phase.")

Đã lưu /content/drive/MyDrive/MOOCCubeX/Dataset/Data_cleaned/video_phase_1.csv: 12424 dòng, 15 cột
Đã lưu /content/drive/MyDrive/MOOCCubeX/Dataset/Data_cleaned/video_phase_2.csv: 2323 dòng, 15 cột
Đã lưu /content/drive/MyDrive/MOOCCubeX/Dataset/Data_cleaned/video_phase_3.csv: 418 dòng, 15 cột
Đã lưu /content/drive/MyDrive/MOOCCubeX/Dataset/Data_cleaned/video_phase_4.csv: 266 dòng, 15 cột

Hoàn tất xử lý và lưu tất cả 4 phase.

# Kiểm tra lại file

In [ ]:
path_phase_1 = "/kaggle/working/video_phase_1.csv"
path_phase_2 = "/kaggle/working/video_phase_2.csv"
path_phase_3 = "/kaggle/working/video_phase_3.csv"
path_phase_4 = "/kaggle/working/video_phase_4.csv"

## Phase 1

In [ ]:
df_phase_1 = pd.read_csv(path_phase_1)

print(df_phase_1.info())
df_phase_1.head()

## Phase 2

In [ ]:
df_phase_2 = pd.read_csv(path_phase_2)

print(df_phase_2.info())
df_phase_2.head()

## Phase 3

In [ ]:
df_phase_3 = pd.read_csv(path_phase_3)

print(df_phase_3.info())
df_phase_3.head()

## Phase 4

In [ ]:
df_phase_4 = pd.read_csv(path_phase_4)

print(df_phase_4.info())
df_phase_4.head()