# Import thư viện và đọc file

In [1]:
import pandas as pd
import numpy as np

file_path_reply = "/kaggle/input/ds317/reply_with_features.csv"
df_reply = pd.read_csv(file_path_reply)
df_reply.info()

print()

file_path_enroll = "/kaggle/input/ds317/label_3_5(have_start_end).csv"
df_enroll = pd.read_csv(file_path_enroll)
df_enroll.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64557 entries, 0 to 64556
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        64557 non-null  object
 1   user_id                   64557 non-null  object
 2   comment_id                64557 non-null  object
 3   course_id                 64557 non-null  object
 4   resource_id               29147 non-null  object
 5   enroll_time               64557 non-null  object
 6   create_comment_time       64557 non-null  object
 7   create_time               64557 non-null  object
 8   days_since_enroll         64557 non-null  int64
 9   days_since_comment        64557 non-null  int64
 10  phase                     64557 non-null  float64
 11  num_words                 64557 non-null  int64
 12  text                      64556 non-null  object
 13  label                     64557 non-null  object
 14  reply_interval            64557 non-null  float64
 15  is_first_reply            64557 non-null  int64
 16  label_encoded             64557 non-null  int64
 17  avg_sentiment_by_user     64557 non-null  float64
 18  sentiment_std_by_user     64557 non-null  float64
 19  reply_count_by_user       64557 non-null  int64
 20  replies_per_comment       64557 non-null  int64
 21  phase_progress_ratio      64557 non-null  float64
 22  reply_delay               64557 non-null  int64
 23  avg_words_by_user         64557 non-null  float64
 24  rolling_sentiment_mean_3  64557 non-null  float64
dtypes: float64(7), int64(8), object(10)
memory usage: 12.3+ MB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24020 entries, 0 to 24019
Data columns (total 23 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        24020 non-null  int64
 1   course_id                         24020 non-null  object
 2   start_date                        24020 non-null  object
 3   end_date                          24020 non-null  object
 4   user_id                           24020 non-null  object
 5   enroll_time                       24020 non-null  object
 6   Video                             24020 non-null  float64
 7   Assignment                        24020 non-null  float64
 8   Exam                              24020 non-null  float64
 9   amount_exercise_each_exam         24020 non-null  float64
 10  total_correct_ratio_exam          24020 non-null  float64
 11  average_correct_ratio_exam        24020 non-null  float64
 12  amount_exercise_each_assignment   24020 non-null  float64
 13  total_correct_ratio_assignment    24020 non-null  float64
 14  average_correct_ratio_assignment  24020 non-null  float64
 15  watched_videos                    24020 non-null  float64
 16  video_counts                      24020 non-null  float64
 17  watch_percent                     24020 non-null  float64
 18  score                             24020 non-null  float64
 19  label_3                           24020 non-null  object
 20  label_5                           24020 non-null  object
 21  course_duration                   24020 non-null  int64
 22  enrollment_to_end                 24020 non-null  int64
dtypes: float64(13), int64(3), object(7)
memory usage: 4.2+ MB

In [2]:
df_reply.head()

,id,user_id,comment_id,course_id,resource_id,enroll_time,create_comment_time,create_time,days_since_enroll,days_since_comment,...,is_first_reply,label_encoded,avg_sentiment_by_user,sentiment_std_by_user,reply_count_by_user,replies_per_comment,phase_progress_ratio,reply_delay,avg_words_by_user,rolling_sentiment_mean_3
0,Rp_84825,U_10036588,Cm_4550589,C_696563,NaN,2020-02-27 19:15:09,2020-03-16 10:40:10,2020-03-17 10:42:19,18,1,...,1,2,1.666667,0.577350,3,1,1.0,1,5.666667,2.000000
1,Rp_96813,U_10036588,Cm_5134420,C_696563,V_1324250,2020-03-25 12:43:09,2020-03-26 00:00:28,2020-03-26 12:27:38,0,0,...,0,1,1.666667,0.577350,3,1,0.5,0,5.666667,1.500000
2,Rp_287394,U_10036588,Cm_13799441,C_696563,NaN,2020-08-04 20:49:49,2020-08-04 21:19:05,2020-08-07 11:12:01,2,2,...,0,2,1.666667,0.577350,3,1,0.5,2,5.666667,1.666667
3,Rp_162566,U_10037312,Cm_7951759,C_936971,NaN,2020-04-28 11:00:03,2020-05-12 10:07:53,2020-05-12 10:08:11,13,0,...,1,2,2.000000,0.000000,1,1,1.0,0,8.000000,2.000000
4,Rp_280363,U_10060289,Cm_13146887,C_948428,NaN,2020-07-03 23:15:34,2020-07-03 23:43:28,2020-07-25 17:09:21,21,21,...,1,2,1.000000,1.414214,2,2,1.0,21,1.000000,2.000000

In [3]:
df_enroll.head()

,Unnamed: 0,course_id,start_date,end_date,user_id,enroll_time,Video,Assignment,Exam,amount_exercise_each_exam,...,total_correct_ratio_assignment,average_correct_ratio_assignment,watched_videos,video_counts,watch_percent,score,label_3,label_5,course_duration,enrollment_to_end
0,15286,C_682697,2019-08-01,2020-07-31,U_12987634,2020-05-20 17:00:46,40.0,60.0,0.0,0.0,...,1.00,1.00,0.0,0.0,0.0,60.0,B,C,365,71
1,15102,C_682679,2019-08-01,2020-07-31,U_28140459,2020-05-05 23:53:27,40.0,60.0,0.0,0.0,...,2.00,1.00,0.0,0.0,0.0,60.0,B,C,365,86
2,15101,C_682679,2019-08-01,2020-07-31,U_27428127,2020-05-26 11:36:24,40.0,60.0,0.0,0.0,...,10.83,0.72,0.0,0.0,0.0,43.2,E,D,365,65
3,15100,C_682679,2019-08-01,2020-07-31,U_25721362,2020-04-08 16:00:45,40.0,60.0,0.0,0.0,...,6.00,0.67,0.0,0.0,0.0,40.2,E,D,365,113
4,15099,C_682679,2019-08-01,2020-07-31,U_25321487,2020-06-19 01:17:53,40.0,60.0,0.0,0.0,...,1.00,1.00,0.0,0.0,0.0,60.0,B,C,365,41

# Merge file

In [4]:
# Merge df_reply với df_enroll
merged_df = df_enroll.merge(
    df_reply,
    on=["user_id", "course_id", "enroll_time"],
    how="inner"
)

print("Trước khi merge:", len(df_enroll))
print("Sau khi merge:", len(merged_df))

# Lưu merged_df ra file csv
merged_file = "merged_df.csv"
merged_df.to_csv(merged_file, index=False)
print(f"Đã lưu merged_df ra file: {merged_file}")

display(merged_df.head())

Trước khi merge: 24020
Sau khi merge: 62
Đã lưu merged_df ra file: merged_df.csv

,Unnamed: 0,course_id,start_date,end_date,user_id,enroll_time,Video,Assignment,Exam,amount_exercise_each_exam,...,is_first_reply,label_encoded,avg_sentiment_by_user,sentiment_std_by_user,reply_count_by_user,replies_per_comment,phase_progress_ratio,reply_delay,avg_words_by_user,rolling_sentiment_mean_3
0,36282,C_797853,2019-09-23,2020-01-12,U_11567772,2019-09-24 17:52:08,50.0,30.0,20.0,0.0,...,1,1,1.0,0.000000,1,1,1.0,0,17.0,1.0
1,7942,C_682392,2019-09-25,2020-01-10,U_4663892,2019-12-28 19:57:52,55.0,25.0,20.0,1.0,...,1,1,1.0,0.000000,1,1,1.0,0,2.0,1.0
2,7904,C_682392,2019-09-25,2020-01-10,U_4661657,2019-12-28 23:17:47,55.0,25.0,20.0,1.0,...,1,1,0.5,0.707107,2,2,1.0,0,3.5,1.0
3,7904,C_682392,2019-09-25,2020-01-10,U_4661657,2019-12-28 23:17:47,55.0,25.0,20.0,1.0,...,1,0,0.5,0.707107,2,1,1.0,0,3.5,0.5
4,7939,C_682392,2019-09-25,2020-01-10,U_4663710,2019-12-28 15:45:19,55.0,25.0,20.0,1.0,...,1,1,1.0,0.000000,2,2,1.0,0,2.0,1.0

In [5]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 45 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        62 non-null     int64
 1   course_id                         62 non-null     object
 2   start_date                        62 non-null     object
 3   end_date                          62 non-null     object
 4   user_id                           62 non-null     object
 5   enroll_time                       62 non-null     object
 6   Video                             62 non-null     float64
 7   Assignment                        62 non-null     float64
 8   Exam                              62 non-null     float64
 9   amount_exercise_each_exam         62 non-null     float64
 10  total_correct_ratio_exam          62 non-null     float64
 11  average_correct_ratio_exam        62 non-null     float64
 12  amount_exercise_each_assignment   62 non-null     float64
 13  total_correct_ratio_assignment    62 non-null     float64
 14  average_correct_ratio_assignment  62 non-null     float64
 15  watched_videos                    62 non-null     float64
 16  video_counts                      62 non-null     float64
 17  watch_percent                     62 non-null     float64
 18  score                             62 non-null     float64
 19  label_3                           62 non-null     object
 20  label_5                           62 non-null     object
 21  course_duration                   62 non-null     int64
 22  enrollment_to_end                 62 non-null     int64
 23  id                                62 non-null     object
 24  comment_id                        62 non-null     object
 25  resource_id                       20 non-null     object
 26  create_comment_time               62 non-null     object
 27  create_time                       62 non-null     object
 28  days_since_enroll                 62 non-null     int64
 29  days_since_comment                62 non-null     int64
 30  phase                             62 non-null     float64
 31  num_words                         62 non-null     int64
 32  text                              62 non-null     object
 33  label                             62 non-null     object
 34  reply_interval                    62 non-null     float64
 35  is_first_reply                    62 non-null     int64
 36  label_encoded                     62 non-null     int64
 37  avg_sentiment_by_user             62 non-null     float64
 38  sentiment_std_by_user             62 non-null     float64
 39  reply_count_by_user               62 non-null     int64
 40  replies_per_comment               62 non-null     int64
 41  phase_progress_ratio              62 non-null     float64
 42  reply_delay                       62 non-null     int64
 43  avg_words_by_user                 62 non-null     float64
 44  rolling_sentiment_mean_3          62 non-null     float64
dtypes: float64(20), int64(11), object(14)
memory usage: 21.9+ KB

# Chia dữ liệu thành 4 phase dựa trên cột ['days_since_enroll']

## Hàm gán phase

In [6]:
def assign_phase(days):
    if pd.isna(days):
        return None
    if days <= 14:
        return 'Phase_1'
    elif days <= 28:
        return 'Phase_2'
    elif days <= 42:
        return 'Phase_3'
    else:
        return 'Phase_4'

## Thực hiện gán phase

In [7]:
# Đọc file
print("Đang đọc merged_df.csv...")
df = pd.read_csv("/kaggle/working/merged_df.csv")
print(f"Số dòng ban đầu: {len(df)}")

# Gán giá trị phase cho từng dòng dựa vào số ngày kể từ khi ghi danh
print("Đang gán phase...")
df['phase'] = df['days_since_enroll'].apply(assign_phase)  # Hàm assign_phase sẽ phân loại phase (1, 2, 3, 4)

df = df[df['phase'].notna()]
print(f"Số dòng sau khi gán phase: {len(df)}")

print("\nPhân bố phase:")
print(df['phase'].value_counts().sort_index())  # Đếm số dòng theo từng phase

Đang đọc merged_df.csv...
Số dòng ban đầu: 62
Đang gán phase...
Số dòng sau khi gán phase: 62

Phân bố phase:
phase
Phase_1    38
Phase_2    11
Phase_3     8
Phase_4     5
Name: count, dtype: int64

## Kiểm tra trùng và groupby

In [8]:
phases = ['Phase_1', 'Phase_2', 'Phase_3', 'Phase_4']
group_cols = ['user_id', 'course_id', 'enroll_time']

agg_results = {}

for i, phase in enumerate(phases, start=1):
    print(f"\n=== {phase} ===")

    df_phase = df[df['phase'] == phase].copy()

    # Bỏ cột không cần
    drop_cols = ['label_encoded', 'is_first_reply', 'days_since_enroll']
    df_phase = df_phase.drop(columns=drop_cols, errors='ignore')

    # Kiểm tra trùng
    num_dups_before = df_phase.duplicated(subset=group_cols, keep=False).sum()
    print(f"Trước khi gộp: {num_dups_before} bản ghi trùng dựa trên {group_cols}.")

    # Cột numeric (ngoại trừ 'phase')
    numeric_cols = df_phase.select_dtypes(include=['int64', 'float64']).columns.tolist()
    numeric_cols = [c for c in numeric_cols]

    # Tổng và trung bình
    sum_cols = ['num_words']
    mean_cols = [c for c in numeric_cols if c not in sum_cols]

    agg_dict = {col: 'mean' for col in mean_cols}
    for c in sum_cols:
        agg_dict[c] = 'sum'

    # Đếm sentiment
    sentiment_counts = (
        df_phase
        .groupby(group_cols + ['label'])
        .size()
        .unstack(fill_value=0)
        .rename(columns=lambda x: f"total_{x.lower()}")
        .reset_index()
    )

    # Gộp numeric
    agg_numeric = (
        df_phase
        .groupby(group_cols, as_index=False)
        .agg(agg_dict)
        .sort_values(by=group_cols)
        .reset_index(drop=True)
    )

    # Merge 2 phần
    agg_df = pd.merge(agg_numeric, sentiment_counts, on=group_cols, how='left')

    # Đảm bảo luôn có 3 cột này trong file
    for c in ['total_negative', 'total_neutral', 'total_positive']:
        if c not in agg_df.columns:
            agg_df[c] = 0

    # Gán số phase (1, 2, 3, 4)
    agg_df['phase'] = i
    agg_results[i] = agg_df

print("\nHoàn tất gộp dữ liệu tất cả phase.")

=== Phase_1 ===
Trước khi gộp: 16 bản ghi trùng dựa trên ['user_id', 'course_id', 'enroll_time'].

=== Phase_2 ===
Trước khi gộp: 4 bản ghi trùng dựa trên ['user_id', 'course_id', 'enroll_time'].

=== Phase_3 ===
Trước khi gộp: 0 bản ghi trùng dựa trên ['user_id', 'course_id', 'enroll_time'].

=== Phase_4 ===
Trước khi gộp: 0 bản ghi trùng dựa trên ['user_id', 'course_id', 'enroll_time'].

Hoàn tất gộp dữ liệu tất cả phase.

In [9]:
# Kiểm tra dữ liệu sau groupby
for phase, agg_df in agg_results.items():
    num_dups_after = agg_df.duplicated(subset=group_cols, keep=False).sum()
    print(f"\n{phase}: Còn {num_dups_after} bản ghi trùng sau khi gộp.")
    
    if num_dups_after != 0:
        print("Vẫn còn trùng, cần kiểm tra logic groupby.")

1: Còn 0 bản ghi trùng sau khi gộp.

2: Còn 0 bản ghi trùng sau khi gộp.

3: Còn 0 bản ghi trùng sau khi gộp.

4: Còn 0 bản ghi trùng sau khi gộp.

## Lưu file

In [10]:
# Lưu phase vào 4 file
for phase, agg_df in agg_results.items():
    filename = f"reply_phase_{phase}.csv"
    agg_df.to_csv(filename, index=False)
    print(f"Đã lưu {filename}: {len(agg_df)} dòng, {len(agg_df.columns)} cột")

print("\nHoàn tất xử lý và lưu tất cả 4 phase.")

Đã lưu reply_phase_1.csv: 30 dòng, 34 cột
Đã lưu reply_phase_2.csv: 9 dòng, 34 cột
Đã lưu reply_phase_3.csv: 8 dòng, 34 cột
Đã lưu reply_phase_4.csv: 5 dòng, 34 cột

Hoàn tất xử lý và lưu tất cả 4 phase.

# Kiểm tra lại file

In [11]:
path_phase_1 = "/kaggle/working/reply_phase_1.csv"
path_phase_2 = "/kaggle/working/reply_phase_2.csv"
path_phase_3 = "/kaggle/working/reply_phase_3.csv"
path_phase_4 = "/kaggle/working/reply_phase_4.csv"

## Phase 1

In [12]:
df_phase_1 = pd.read_csv(path_phase_1)

print(df_phase_1.info())
df_phase_1.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 34 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   user_id                           30 non-null     object
 1   course_id                         30 non-null     object
 2   enroll_time                       30 non-null     object
 3   Unnamed: 0                        30 non-null     float64
 4   Video                             30 non-null     float64
 5   Assignment                        30 non-null     float64
 6   Exam                              30 non-null     float64
 7   amount_exercise_each_exam         30 non-null     float64
 8   total_correct_ratio_exam          30 non-null     float64
 9   average_correct_ratio_exam        30 non-null     float64
 10  amount_exercise_each_assignment   30 non-null     float64
 11  total_correct_ratio_assignment    30 non-null     float64
 12  average_correct_ratio_assignment  30 non-null     float64
 13  watched_videos                    30 non-null     float64
 14  video_counts                      30 non-null     float64
 15  watch_percent                     30 non-null     float64
 16  score                             30 non-null     float64
 17  course_duration                   30 non-null     float64
 18  enrollment_to_end                 30 non-null     float64
 19  days_since_comment                30 non-null     float64
 20  reply_interval                    30 non-null     float64
 21  avg_sentiment_by_user             30 non-null     float64
 22  sentiment_std_by_user             30 non-null     float64
 23  reply_count_by_user               30 non-null     float64
 24  replies_per_comment               30 non-null     float64
 25  phase_progress_ratio              30 non-null     float64
 26  reply_delay                       30 non-null     float64
 27  avg_words_by_user                 30 non-null     float64
 28  rolling_sentiment_mean_3          30 non-null     float64
 29  num_words                         30 non-null     int64
 30  total_negative                    30 non-null     int64
 31  total_neutral                     30 non-null     int64
 32  total_positive                    30 non-null     int64
 33  phase                             30 non-null     int64
dtypes: float64(26), int64(5), object(3)
memory usage: 8.1+ KB
None

,user_id,course_id,enroll_time,Unnamed: 0,Video,Assignment,Exam,amount_exercise_each_exam,total_correct_ratio_exam,average_correct_ratio_exam,...,replies_per_comment,phase_progress_ratio,reply_delay,avg_words_by_user,rolling_sentiment_mean_3,num_words,total_negative,total_neutral,total_positive,phase
0,U_11377760,C_2286754,2020-10-24 17:54:48,84112.0,10.0,50.0,40.0,0.0,0.0,0.0,...,2.0,1.0,0.0,7.0,1.0,7,0,1,0,1
1,U_11504112,C_2286754,2020-10-24 19:53:59,84132.0,10.0,50.0,40.0,0.0,0.0,0.0,...,3.0,1.0,0.0,16.0,1.0,32,0,2,0,1
2,U_11504122,C_2286754,2020-10-24 19:58:51,84133.0,10.0,50.0,40.0,0.0,0.0,0.0,...,2.0,1.0,0.0,21.0,1.0,21,0,1,0,1
3,U_11504208,C_2286754,2020-10-24 20:28:25,84139.0,10.0,50.0,40.0,0.0,0.0,0.0,...,2.0,1.0,0.0,5.0,1.0,5,0,1,0,1
4,U_11504615,C_2286754,2020-10-24 17:26:22,84147.0,10.0,50.0,40.0,0.0,0.0,0.0,...,3.0,1.0,3.0,20.0,1.0,20,0,1,0,1

## Phase 2

In [13]:
df_phase_2 = pd.read_csv(path_phase_2)

print(df_phase_2.info())
df_phase_2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 34 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   user_id                           9 non-null      object
 1   course_id                         9 non-null      object
 2   enroll_time                       9 non-null      object
 3   Unnamed: 0                        9 non-null      float64
 4   Video                             9 non-null      float64
 5   Assignment                        9 non-null      float64
 6   Exam                              9 non-null      float64
 7   amount_exercise_each_exam         9 non-null      float64
 8   total_correct_ratio_exam          9 non-null      float64
 9   average_correct_ratio_exam        9 non-null      float64
 10  amount_exercise_each_assignment   9 non-null      float64
 11  total_correct_ratio_assignment    9 non-null      float64
 12  average_correct_ratio_assignment  9 non-null      float64
 13  watched_videos                    9 non-null      float64
 14  video_counts                      9 non-null      float64
 15  watch_percent                     9 non-null      float64
 16  score                             9 non-null      float64
 17  course_duration                   9 non-null      float64
 18  enrollment_to_end                 9 non-null      float64
 19  days_since_comment                9 non-null      float64
 20  reply_interval                    9 non-null      float64
 21  avg_sentiment_by_user             9 non-null      float64
 22  sentiment_std_by_user             9 non-null      float64
 23  reply_count_by_user               9 non-null      float64
 24  replies_per_comment               9 non-null      float64
 25  phase_progress_ratio              9 non-null      float64
 26  reply_delay                       9 non-null      float64
 27  avg_words_by_user                 9 non-null      float64
 28  rolling_sentiment_mean_3          9 non-null      float64
 29  num_words                         9 non-null      int64
 30  total_negative                    9 non-null      int64
 31  total_neutral                     9 non-null      int64
 32  total_positive                    9 non-null      int64
 33  phase                             9 non-null      int64
dtypes: float64(26), int64(5), object(3)
memory usage: 2.5+ KB
None

,user_id,course_id,enroll_time,Unnamed: 0,Video,Assignment,Exam,amount_exercise_each_exam,total_correct_ratio_exam,average_correct_ratio_exam,...,replies_per_comment,phase_progress_ratio,reply_delay,avg_words_by_user,rolling_sentiment_mean_3,num_words,total_negative,total_neutral,total_positive,phase
0,U_11567772,C_797853,2019-09-24 17:52:08,36282.0,50.0,30.0,20.0,0.0,0.0,0.0,...,1.0,1.0,0.0,17.0,1.00,17,0,1,0,2
1,U_12292667,C_948488,2020-03-06 14:23:29,65273.0,20.0,40.0,40.0,1.0,0.9,0.9,...,2.0,1.0,0.0,1.0,1.75,2,0,1,1,2
2,U_12699624,C_1918351,2020-09-07 22:25:05,75287.0,20.0,20.0,60.0,0.0,0.0,0.0,...,1.0,1.0,0.0,14.0,1.00,14,0,1,0,2
3,U_14251773,C_948259,2020-02-13 18:49:25,59490.0,10.0,70.0,20.0,1.0,1.0,1.0,...,1.0,1.0,0.0,32.0,1.00,32,0,1,0,2
4,U_2114799,C_948093,2020-08-11 11:53:42,56599.0,65.0,15.0,20.0,0.0,0.0,0.0,...,2.0,1.0,0.0,16.0,1.00,16,0,1,0,2

## Phase 3

In [14]:
df_phase_3 = pd.read_csv(path_phase_3)

print(df_phase_3.info())
df_phase_3.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 34 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   user_id                           8 non-null      object
 1   course_id                         8 non-null      object
 2   enroll_time                       8 non-null      object
 3   Unnamed: 0                        8 non-null      float64
 4   Video                             8 non-null      float64
 5   Assignment                        8 non-null      float64
 6   Exam                              8 non-null      float64
 7   amount_exercise_each_exam         8 non-null      float64
 8   total_correct_ratio_exam          8 non-null      float64
 9   average_correct_ratio_exam        8 non-null      float64
 10  amount_exercise_each_assignment   8 non-null      float64
 11  total_correct_ratio_assignment    8 non-null      float64
 12  average_correct_ratio_assignment  8 non-null      float64
 13  watched_videos                    8 non-null      float64
 14  video_counts                      8 non-null      float64
 15  watch_percent                     8 non-null      float64
 16  score                             8 non-null      float64
 17  course_duration                   8 non-null      float64
 18  enrollment_to_end                 8 non-null      float64
 19  days_since_comment                8 non-null      float64
 20  reply_interval                    8 non-null      float64
 21  avg_sentiment_by_user             8 non-null      float64
 22  sentiment_std_by_user             8 non-null      float64
 23  reply_count_by_user               8 non-null      float64
 24  replies_per_comment               8 non-null      float64
 25  phase_progress_ratio              8 non-null      float64
 26  reply_delay                       8 non-null      float64
 27  avg_words_by_user                 8 non-null      float64
 28  rolling_sentiment_mean_3          8 non-null      float64
 29  num_words                         8 non-null      int64
 30  total_negative                    8 non-null      int64
 31  total_neutral                     8 non-null      int64
 32  total_positive                    8 non-null      int64
 33  phase                             8 non-null      int64
dtypes: float64(26), int64(5), object(3)
memory usage: 2.3+ KB
None

,user_id,course_id,enroll_time,Unnamed: 0,Video,Assignment,Exam,amount_exercise_each_exam,total_correct_ratio_exam,average_correct_ratio_exam,...,replies_per_comment,phase_progress_ratio,reply_delay,avg_words_by_user,rolling_sentiment_mean_3,num_words,total_negative,total_neutral,total_positive,phase
0,U_11847142,C_947239,2020-02-25 12:01:54,49396.0,20.0,55.0,25.0,1.0,0.57,0.57,...,1.0,1.0,0.0,3.0,0.0,3,1,0,0,3
1,U_11847224,C_947239,2020-02-25 12:03:11,49441.0,20.0,55.0,25.0,1.0,0.67,0.67,...,1.0,1.0,0.0,1.0,1.0,1,0,1,0,3
2,U_17981079,C_948259,2020-05-28 16:49:13,59541.0,10.0,70.0,20.0,0.0,0.00,0.00,...,1.0,1.0,0.0,9.0,1.0,9,0,1,0,3
3,U_2239464,C_948093,2020-08-13 22:53:52,56615.0,65.0,15.0,20.0,0.0,0.00,0.00,...,2.0,1.0,0.0,2.0,1.0,2,0,1,0,3
4,U_30935297,C_1886672,2020-07-11 22:55:46,70650.0,15.0,55.0,30.0,0.0,0.00,0.00,...,1.0,1.0,0.0,15.0,1.0,15,0,1,0,3

## Phase 4

In [15]:
df_phase_4 = pd.read_csv(path_phase_4)

print(df_phase_4.info())
df_phase_4.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 34 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   user_id                           5 non-null      object
 1   course_id                         5 non-null      object
 2   enroll_time                       5 non-null      object
 3   Unnamed: 0                        5 non-null      float64
 4   Video                             5 non-null      float64
 5   Assignment                        5 non-null      float64
 6   Exam                              5 non-null      float64
 7   amount_exercise_each_exam         5 non-null      float64
 8   total_correct_ratio_exam          5 non-null      float64
 9   average_correct_ratio_exam        5 non-null      float64
 10  amount_exercise_each_assignment   5 non-null      float64
 11  total_correct_ratio_assignment    5 non-null      float64
 12  average_correct_ratio_assignment  5 non-null      float64
 13  watched_videos                    5 non-null      float64
 14  video_counts                      5 non-null      float64
 15  watch_percent                     5 non-null      float64
 16  score                             5 non-null      float64
 17  course_duration                   5 non-null      float64
 18  enrollment_to_end                 5 non-null      float64
 19  days_since_comment                5 non-null      float64
 20  reply_interval                    5 non-null      float64
 21  avg_sentiment_by_user             5 non-null      float64
 22  sentiment_std_by_user             5 non-null      float64
 23  reply_count_by_user               5 non-null      float64
 24  replies_per_comment               5 non-null      float64
 25  phase_progress_ratio              5 non-null      float64
 26  reply_delay                       5 non-null      float64
 27  avg_words_by_user                 5 non-null      float64
 28  rolling_sentiment_mean_3          5 non-null      float64
 29  num_words                         5 non-null      int64
 30  total_neutral                     5 non-null      int64
 31  total_negative                    5 non-null      int64
 32  total_positive                    5 non-null      int64
 33  phase                             5 non-null      int64
dtypes: float64(26), int64(5), object(3)
memory usage: 1.5+ KB
None

,user_id,course_id,enroll_time,Unnamed: 0,Video,Assignment,Exam,amount_exercise_each_exam,total_correct_ratio_exam,average_correct_ratio_exam,...,replies_per_comment,phase_progress_ratio,reply_delay,avg_words_by_user,rolling_sentiment_mean_3,num_words,total_neutral,total_negative,total_positive,phase
0,U_14252871,C_948259,2020-02-19 11:03:23,59491.0,10.0,70.0,20.0,1.0,0.80,0.80,...,1.0,1.0,0.0,4.0,1.0,4,1,0,0,4
1,U_17143197,C_949541,2020-05-04 20:38:20,66871.0,50.0,50.0,0.0,0.0,0.00,0.00,...,1.0,1.0,0.0,3.0,1.0,3,1,0,0,4
2,U_22852107,C_947239,2020-03-28 20:26:01,49725.0,20.0,55.0,25.0,1.0,0.87,0.87,...,1.0,1.0,0.0,6.0,1.0,6,1,0,0,4
3,U_33093539,C_797853,2020-09-26 11:23:04,36576.0,50.0,30.0,20.0,0.0,0.00,0.00,...,1.0,1.0,0.0,127.0,1.0,127,1,0,0,4
4,U_6069192,C_948259,2020-01-04 17:06:33,58931.0,10.0,70.0,20.0,1.0,0.80,0.80,...,2.0,1.0,0.0,3.0,1.0,3,1,0,0,4