# Import thư viện, đọc và merge file

In [1]:
import pandas as pd
import numpy as np

path_phase_files = [
    "/kaggle/input/ds317/phase_1_sentiment.csv",
    "/kaggle/input/ds317/phase_2_sentiment.csv",
    "/kaggle/input/ds317/phase_3 _sentiment.csv",
    "/kaggle/input/ds317/phase_4 _sentiment.csv"
]
phase_dfs = [pd.read_csv(path) for path in path_phase_files]
df_comment = pd.concat(phase_dfs, ignore_index=True)

print()

file_path_enroll = "/kaggle/input/ds317/label_3_5(have_start_end).csv"
df_enroll = pd.read_csv(file_path_enroll)

In [2]:
df_comment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4496862 entries, 0 to 4496861
Data columns (total 20 columns):
 #   Column                Dtype
---  ------                -----
 0   course_id             object
 1   comment_id            object
 2   id                    object
 3   user_id               object
 4   text                  object
 5   resource_id           object
 6   create_time           object
 7   year_month            object
 8   enroll_time           object
 9   days_since_enroll     int64
 10  phase                 float64
 11  num_words             int64
 12  comment_count         float64
 13  total_words           float64
 14  time_bin              int64
 15  entropy_time_comment  float64
 16  negative              int64
 17  neutral               int64
 18  positive              int64
 19  Unnamed: 0            float64
dtypes: float64(5), int64(6), object(9)
memory usage: 686.2+ MB

# Merge file

In [3]:
# Merge df_reply với df_enroll
merged_df = df_enroll.merge(
    df_comment,
    on=["user_id", "course_id", "enroll_time"],
    how="inner"
)

print("Trước khi merge:", len(df_enroll))
print("Sau khi merge:", len(merged_df))

# Lưu merged_df ra file csv
merged_file = "merged_df.csv"
merged_df.to_csv(merged_file, index=False)
print(f"Đã lưu merged_df ra file: {merged_file}")

display(merged_df.head())

Trước khi merge: 24020
Sau khi merge: 45726
Đã lưu merged_df ra file: merged_df.csv

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Unnamed: 0_x,course_id,start_date,end_date,user_id,enroll_time,Video,Assignment,Exam,amount_exercise_each_exam,...,phase,num_words,comment_count,total_words,time_bin,entropy_time_comment,negative,neutral,positive,Unnamed: 0_y
0,15090,C_682679,2019-08-01,2020-07-31,U_14843232,2020-07-12 16:16:03,40.0,60.0,0.0,0.0,...,1.0,3,1.0,3.0,35,0.0,0,0,1,NaN
1,15280,C_682697,2019-08-01,2020-07-31,U_3558851,2020-06-08 12:17:22,40.0,60.0,0.0,0.0,...,2.0,10,1.0,10.0,46,0.0,0,1,0,NaN
2,15105,C_682679,2019-08-01,2020-07-31,U_29192466,2020-06-04 18:47:48,40.0,60.0,0.0,0.0,...,1.0,9,1.0,9.0,38,0.0,0,0,1,NaN
3,67519,C_1025079,2019-08-01,2020-07-26,U_28763239,2020-03-17 18:17:25,0.0,40.0,60.0,1.0,...,1.0,2,1.0,2.0,46,0.0,0,0,1,NaN
4,21376,C_697684,2019-08-01,2020-07-31,U_28492054,2020-04-22 14:21:47,20.0,80.0,0.0,0.0,...,1.0,2,1.0,2.0,23,0.0,0,0,1,NaN

In [4]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45726 entries, 0 to 45725
Data columns (total 40 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0_x                      45726 non-null  int64
 1   course_id                         45726 non-null  object
 2   start_date                        45726 non-null  object
 3   end_date                          45726 non-null  object
 4   user_id                           45726 non-null  object
 5   enroll_time                       45726 non-null  object
 6   Video                             45726 non-null  float64
 7   Assignment                        45726 non-null  float64
 8   Exam                              45726 non-null  float64
 9   amount_exercise_each_exam         45726 non-null  float64
 10  total_correct_ratio_exam          45726 non-null  float64
 11  average_correct_ratio_exam        45726 non-null  float64
 12  amount_exercise_each_assignment   45726 non-null  float64
 13  total_correct_ratio_assignment    45726 non-null  float64
 14  average_correct_ratio_assignment  45726 non-null  float64
 15  watched_videos                    45726 non-null  float64
 16  video_counts                      45726 non-null  float64
 17  watch_percent                     45726 non-null  float64
 18  score                             45726 non-null  float64
 19  label_3                           45726 non-null  object
 20  label_5                           45726 non-null  object
 21  course_duration                   45726 non-null  int64
 22  enrollment_to_end                 45726 non-null  int64
 23  comment_id                        45726 non-null  object
 24  id                                30990 non-null  object
 25  text                              45726 non-null  object
 26  resource_id                       10656 non-null  object
 27  create_time                       45726 non-null  object
 28  year_month                        45726 non-null  object
 29  days_since_enroll                 45726 non-null  int64
 30  phase                             45726 non-null  float64
 31  num_words                         45726 non-null  int64
 32  comment_count                     45726 non-null  float64
 33  total_words                       45726 non-null  float64
 34  time_bin                          45726 non-null  int64
 35  entropy_time_comment              45726 non-null  float64
 36  negative                          45726 non-null  int64
 37  neutral                           45726 non-null  int64
 38  positive                          45726 non-null  int64
 39  Unnamed: 0_y                      14736 non-null  float64
dtypes: float64(18), int64(9), object(13)
memory usage: 14.0+ MB

# Chia dữ liệu thành 4 phase

## Hàm gán phase

In [5]:
def assign_phase(days):
    if pd.isna(days):
        return None
    if days <= 14:
        return 'Phase_1'
    elif days <= 28:
        return 'Phase_2'
    elif days <= 42:
        return 'Phase_3'
    else:
        return 'Phase_4'

## Thực hiện gán phase

In [6]:
# Đọc file
print("Đang đọc merged_df.csv...")
df = pd.read_csv("/kaggle/working/merged_df.csv")
print(f"Số dòng ban đầu: {len(df)}")

# Gán giá trị phase cho từng dòng dựa vào số ngày kể từ khi ghi danh
print("Đang gán phase...")
df['phase'] = df['days_since_enroll'].apply(assign_phase)  # Hàm assign_phase sẽ phân loại phase (1, 2, 3, 4)

df = df[df['phase'].notna()]
print(f"Số dòng sau khi gán phase: {len(df)}")

print("\nPhân bố phase:")
print(df['phase'].value_counts().sort_index())  # Đếm số dòng theo từng phase

Đang đọc merged_df.csv...
Số dòng ban đầu: 45726
Đang gán phase...
Số dòng sau khi gán phase: 45726

Phân bố phase:
phase
Phase_1    23195
Phase_2     7795
Phase_3     7378
Phase_4     7358
Name: count, dtype: int64

## Kiểm tra trùng và groupby

In [7]:
phases = ['Phase_1', 'Phase_2', 'Phase_3', 'Phase_4']
group_cols = ['user_id', 'course_id', 'enroll_time']
agg_results = {}

for i, phase in enumerate(phases, start=1):
    print(f"\n=== {phase} ===")
    df_phase = df[df['phase'] == phase].copy()
    
    # Bỏ cột không cần
    drop_cols = ['days_since_enroll']
    df_phase = df_phase.drop(columns=drop_cols, errors='ignore')
    
    # Kiểm tra trùng
    num_dups_before = df_phase.duplicated(subset=group_cols, keep=False).sum()
    print(f"Trước khi gộp: {num_dups_before} bản ghi trùng dựa trên {group_cols}.")
    
    # Định nghĩa sentiment columns
    sentiment_cols = ['negative', 'neutral', 'positive']
    
    # Đếm sentiment
    sentiment_counts = (
        df_phase
        .groupby(group_cols, as_index=False)[sentiment_cols]
        .sum()
        .rename(columns={c: f"total_{c}" for c in sentiment_cols})
    )
    
    # Cột numeric (loại trừ sentiment columns)
    numeric_cols = df_phase.select_dtypes(include=['int64', 'float64']).columns.tolist()
    numeric_cols = [c for c in numeric_cols if c not in sentiment_cols]
    
    # Tổng và trung bình
    sum_cols = ['num_words']
    mean_cols = [c for c in numeric_cols if c not in sum_cols]
    
    agg_dict = {col: 'mean' for col in mean_cols}
    for c in sum_cols:
        agg_dict[c] = 'sum'
    
    # Gộp numeric
    agg_numeric = (
        df_phase
        .groupby(group_cols, as_index=False)
        .agg(agg_dict)
        .sort_values(by=group_cols)
        .reset_index(drop=True)
    )
    
    # Merge 2 phần lại
    agg_df = pd.merge(agg_numeric, sentiment_counts, on=group_cols, how='left')
    
    # Đảm bảo 3 cột sentiment luôn tồn tại (phòng trường hợp phase không có đủ 3 loại)
    for c in ['total_negative', 'total_neutral', 'total_positive']:
        if c not in agg_df.columns:
            agg_df[c] = 0
    
    # Gán phase (1, 2, 3, 4)
    agg_df['phase'] = i
    agg_results[i] = agg_df

print("\nHoàn tất gộp dữ liệu tất cả 4 phase.")

=== Phase_1 ===
Trước khi gộp: 21517 bản ghi trùng dựa trên ['user_id', 'course_id', 'enroll_time'].

=== Phase_2 ===
Trước khi gộp: 7008 bản ghi trùng dựa trên ['user_id', 'course_id', 'enroll_time'].

=== Phase_3 ===
Trước khi gộp: 6731 bản ghi trùng dựa trên ['user_id', 'course_id', 'enroll_time'].

=== Phase_4 ===
Trước khi gộp: 6814 bản ghi trùng dựa trên ['user_id', 'course_id', 'enroll_time'].

Hoàn tất gộp dữ liệu tất cả 4 phase.

In [8]:
# Kiểm tra dữ liệu sau groupby
for phase, agg_df in agg_results.items():
    num_dups_after = agg_df.duplicated(subset=group_cols, keep=False).sum()
    print(f"\n{phase}: Còn {num_dups_after} bản ghi trùng sau khi gộp.")
    
    if num_dups_after != 0:
        print("Vẫn còn trùng, cần kiểm tra logic groupby.")

1: Còn 0 bản ghi trùng sau khi gộp.

2: Còn 0 bản ghi trùng sau khi gộp.

3: Còn 0 bản ghi trùng sau khi gộp.

4: Còn 0 bản ghi trùng sau khi gộp.

## Chia file

In [9]:
# Lưu phase vào 4 file
for phase, agg_df in agg_results.items():
    filename = f"comment_phase_{phase}.csv"
    agg_df.to_csv(filename, index=False)
    print(f"Đã lưu {filename}: {len(agg_df)} dòng, {len(agg_df.columns)} cột")

print("\nHoàn tất xử lý và lưu tất cả 4 phase.")

Đã lưu comment_phase_1.csv: 4720 dòng, 29 cột
Đã lưu comment_phase_2.csv: 2045 dòng, 29 cột
Đã lưu comment_phase_3.csv: 1830 dòng, 29 cột
Đã lưu comment_phase_4.csv: 1650 dòng, 29 cột

Hoàn tất xử lý và lưu tất cả 4 phase.

# Kiểm tra lại file

In [10]:
path_phase_1 = "/kaggle/working/comment_phase_1.csv"
path_phase_2 = "/kaggle/working/comment_phase_2.csv"
path_phase_3 = "/kaggle/working/comment_phase_3.csv"
path_phase_4 = "/kaggle/working/comment_phase_4.csv"

## Phase 1

In [11]:
df_phase_1 = pd.read_csv(path_phase_1)

print(df_phase_1.info())
df_phase_1.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4720 entries, 0 to 4719
Data columns (total 29 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   user_id                           4720 non-null   object
 1   course_id                         4720 non-null   object
 2   enroll_time                       4720 non-null   object
 3   Unnamed: 0_x                      4720 non-null   float64
 4   Video                             4720 non-null   float64
 5   Assignment                        4720 non-null   float64
 6   Exam                              4720 non-null   float64
 7   amount_exercise_each_exam         4720 non-null   float64
 8   total_correct_ratio_exam          4720 non-null   float64
 9   average_correct_ratio_exam        4720 non-null   float64
 10  amount_exercise_each_assignment   4720 non-null   float64
 11  total_correct_ratio_assignment    4720 non-null   float64
 12  average_correct_ratio_assignment  4720 non-null   float64
 13  watched_videos                    4720 non-null   float64
 14  video_counts                      4720 non-null   float64
 15  watch_percent                     4720 non-null   float64
 16  score                             4720 non-null   float64
 17  course_duration                   4720 non-null   float64
 18  enrollment_to_end                 4720 non-null   float64
 19  comment_count                     4720 non-null   float64
 20  total_words                       4720 non-null   float64
 21  time_bin                          4720 non-null   float64
 22  entropy_time_comment              4720 non-null   float64
 23  Unnamed: 0_y                      0 non-null      float64
 24  num_words                         4720 non-null   int64
 25  total_negative                    4720 non-null   int64
 26  total_neutral                     4720 non-null   int64
 27  total_positive                    4720 non-null   int64
 28  phase                             4720 non-null   int64
dtypes: float64(21), int64(5), object(3)
memory usage: 1.0+ MB
None

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,user_id,course_id,enroll_time,Unnamed: 0_x,Video,Assignment,Exam,amount_exercise_each_exam,total_correct_ratio_exam,average_correct_ratio_exam,...,comment_count,total_words,time_bin,entropy_time_comment,Unnamed: 0_y,num_words,total_negative,total_neutral,total_positive,phase
0,U_10068981,C_1761358,2020-08-17 13:02:48,68079.0,40.0,60.0,0.0,0.0,0.00,0.00,...,1.0,36.0,29.000000,0.000000,NaN,36,1,0,0,1
1,U_10127138,C_934534,2020-03-18 13:26:25,46972.0,0.0,20.0,80.0,1.0,0.83,0.83,...,2.0,28.0,25.500000,0.693147,NaN,28,0,0,2,1
2,U_10127175,C_934534,2020-03-18 13:34:14,46975.0,0.0,20.0,80.0,1.0,1.00,1.00,...,1.0,2.0,21.000000,0.000000,NaN,2,0,1,0,1
3,U_10127204,C_934534,2020-03-19 17:08:12,46976.0,0.0,20.0,80.0,1.0,0.67,0.67,...,1.0,25.0,20.000000,0.000000,NaN,25,0,0,1,1
4,U_10128005,C_934534,2020-05-22 11:44:02,46977.0,0.0,20.0,80.0,1.0,0.75,0.75,...,7.0,29.0,28.571429,1.549826,NaN,29,0,5,2,1

## Phase 2

In [12]:
df_phase_2 = pd.read_csv(path_phase_2)

print(df_phase_2.info())
df_phase_2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2045 entries, 0 to 2044
Data columns (total 29 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   user_id                           2045 non-null   object
 1   course_id                         2045 non-null   object
 2   enroll_time                       2045 non-null   object
 3   Unnamed: 0_x                      2045 non-null   float64
 4   Video                             2045 non-null   float64
 5   Assignment                        2045 non-null   float64
 6   Exam                              2045 non-null   float64
 7   amount_exercise_each_exam         2045 non-null   float64
 8   total_correct_ratio_exam          2045 non-null   float64
 9   average_correct_ratio_exam        2045 non-null   float64
 10  amount_exercise_each_assignment   2045 non-null   float64
 11  total_correct_ratio_assignment    2045 non-null   float64
 12  average_correct_ratio_assignment  2045 non-null   float64
 13  watched_videos                    2045 non-null   float64
 14  video_counts                      2045 non-null   float64
 15  watch_percent                     2045 non-null   float64
 16  score                             2045 non-null   float64
 17  course_duration                   2045 non-null   float64
 18  enrollment_to_end                 2045 non-null   float64
 19  comment_count                     2045 non-null   float64
 20  total_words                       2045 non-null   float64
 21  time_bin                          2045 non-null   float64
 22  entropy_time_comment              2045 non-null   float64
 23  Unnamed: 0_y                      0 non-null      float64
 24  num_words                         2045 non-null   int64
 25  total_negative                    2045 non-null   int64
 26  total_neutral                     2045 non-null   int64
 27  total_positive                    2045 non-null   int64
 28  phase                             2045 non-null   int64
dtypes: float64(21), int64(5), object(3)
memory usage: 463.4+ KB
None

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,user_id,course_id,enroll_time,Unnamed: 0_x,Video,Assignment,Exam,amount_exercise_each_exam,total_correct_ratio_exam,average_correct_ratio_exam,...,comment_count,total_words,time_bin,entropy_time_comment,Unnamed: 0_y,num_words,total_negative,total_neutral,total_positive,phase
0,U_10125830,C_934534,2020-03-18 14:00:23,46970.0,0.0,20.0,80.0,1.0,0.67,0.67,...,1.0,33.0,27.000000,0.000000,NaN,33,0,0,1,2
1,U_10127123,C_934534,2020-03-18 16:25:48,46971.0,0.0,20.0,80.0,0.0,0.00,0.00,...,3.0,5.0,24.666667,0.636514,NaN,5,0,2,1,2
2,U_10128161,C_934534,2020-03-18 13:51:45,46979.0,0.0,20.0,80.0,1.0,0.75,0.75,...,1.0,13.0,31.000000,0.000000,NaN,13,0,0,1,2
3,U_10130442,C_934534,2020-03-18 13:50:55,46982.0,0.0,20.0,80.0,1.0,0.58,0.58,...,1.0,13.0,28.000000,0.000000,NaN,13,0,0,1,2
4,U_10138543,C_934534,2020-03-18 15:08:52,46990.0,0.0,20.0,80.0,1.0,0.92,0.92,...,2.0,6.0,23.500000,0.693147,NaN,6,0,2,0,2

## Phase 3

In [13]:
df_phase_3 = pd.read_csv(path_phase_3)

print(df_phase_3.info())
df_phase_3.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1830 entries, 0 to 1829
Data columns (total 29 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   user_id                           1830 non-null   object
 1   course_id                         1830 non-null   object
 2   enroll_time                       1830 non-null   object
 3   Unnamed: 0_x                      1830 non-null   float64
 4   Video                             1830 non-null   float64
 5   Assignment                        1830 non-null   float64
 6   Exam                              1830 non-null   float64
 7   amount_exercise_each_exam         1830 non-null   float64
 8   total_correct_ratio_exam          1830 non-null   float64
 9   average_correct_ratio_exam        1830 non-null   float64
 10  amount_exercise_each_assignment   1830 non-null   float64
 11  total_correct_ratio_assignment    1830 non-null   float64
 12  average_correct_ratio_assignment  1830 non-null   float64
 13  watched_videos                    1830 non-null   float64
 14  video_counts                      1830 non-null   float64
 15  watch_percent                     1830 non-null   float64
 16  score                             1830 non-null   float64
 17  course_duration                   1830 non-null   float64
 18  enrollment_to_end                 1830 non-null   float64
 19  comment_count                     1830 non-null   float64
 20  total_words                       1830 non-null   float64
 21  time_bin                          1830 non-null   float64
 22  entropy_time_comment              1830 non-null   float64
 23  Unnamed: 0_y                      1830 non-null   float64
 24  num_words                         1830 non-null   int64
 25  total_negative                    1830 non-null   int64
 26  total_neutral                     1830 non-null   int64
 27  total_positive                    1830 non-null   int64
 28  phase                             1830 non-null   int64
dtypes: float64(21), int64(5), object(3)
memory usage: 414.7+ KB
None

,user_id,course_id,enroll_time,Unnamed: 0_x,Video,Assignment,Exam,amount_exercise_each_exam,total_correct_ratio_exam,average_correct_ratio_exam,...,comment_count,total_words,time_bin,entropy_time_comment,Unnamed: 0_y,num_words,total_negative,total_neutral,total_positive,phase
0,U_1002784,C_1756056,2020-10-13 17:13:34,68020.0,30.0,70.0,0.0,0.0,0.00,0.00,...,3.0,119.0,32.666667,1.098612,668982.333333,119,1,0,2,3
1,U_10072834,C_947260,2020-02-24 07:56:01,51737.0,60.0,20.0,20.0,1.0,0.40,0.40,...,1.0,4.0,39.000000,0.000000,194498.000000,4,0,1,0,3
2,U_10127138,C_934534,2020-03-18 13:26:25,46972.0,0.0,20.0,80.0,1.0,0.83,0.83,...,3.0,16.0,36.000000,1.098612,255816.000000,16,0,3,0,3
3,U_10127175,C_934534,2020-03-18 13:34:14,46975.0,0.0,20.0,80.0,1.0,1.00,1.00,...,3.0,6.0,17.666667,0.636514,256129.333333,6,0,3,0,3
4,U_10128005,C_934534,2020-05-22 11:44:02,46977.0,0.0,20.0,80.0,1.0,0.75,0.75,...,1.0,4.0,44.000000,0.000000,537705.000000,4,0,1,0,3

## Phase 4

In [14]:
df_phase_4 = pd.read_csv(path_phase_4)

print(df_phase_4.info())
df_phase_4.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1650 entries, 0 to 1649
Data columns (total 29 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   user_id                           1650 non-null   object
 1   course_id                         1650 non-null   object
 2   enroll_time                       1650 non-null   object
 3   Unnamed: 0_x                      1650 non-null   float64
 4   Video                             1650 non-null   float64
 5   Assignment                        1650 non-null   float64
 6   Exam                              1650 non-null   float64
 7   amount_exercise_each_exam         1650 non-null   float64
 8   total_correct_ratio_exam          1650 non-null   float64
 9   average_correct_ratio_exam        1650 non-null   float64
 10  amount_exercise_each_assignment   1650 non-null   float64
 11  total_correct_ratio_assignment    1650 non-null   float64
 12  average_correct_ratio_assignment  1650 non-null   float64
 13  watched_videos                    1650 non-null   float64
 14  video_counts                      1650 non-null   float64
 15  watch_percent                     1650 non-null   float64
 16  score                             1650 non-null   float64
 17  course_duration                   1650 non-null   float64
 18  enrollment_to_end                 1650 non-null   float64
 19  comment_count                     1650 non-null   float64
 20  total_words                       1650 non-null   float64
 21  time_bin                          1650 non-null   float64
 22  entropy_time_comment              1650 non-null   float64
 23  Unnamed: 0_y                      1650 non-null   float64
 24  num_words                         1650 non-null   int64
 25  total_negative                    1650 non-null   int64
 26  total_neutral                     1650 non-null   int64
 27  total_positive                    1650 non-null   int64
 28  phase                             1650 non-null   int64
dtypes: float64(21), int64(5), object(3)
memory usage: 374.0+ KB
None

,user_id,course_id,enroll_time,Unnamed: 0_x,Video,Assignment,Exam,amount_exercise_each_exam,total_correct_ratio_exam,average_correct_ratio_exam,...,comment_count,total_words,time_bin,entropy_time_comment,Unnamed: 0_y,num_words,total_negative,total_neutral,total_positive,phase
0,U_10125830,C_934534,2020-03-18 14:00:23,46970.0,0.0,20.0,80.0,1.0,0.67,0.67,...,4.0,10.0,36.500000,1.039721,204075.250000,10,0,3,1,4
1,U_10127123,C_934534,2020-03-18 16:25:48,46971.0,0.0,20.0,80.0,0.0,0.00,0.00,...,1.0,2.0,31.000000,0.000000,211237.000000,2,0,1,0,4
2,U_10130400,C_934534,2020-03-18 14:18:11,46980.0,0.0,20.0,80.0,1.0,0.67,0.67,...,2.0,27.0,20.000000,0.693147,211979.000000,27,0,1,1,4
3,U_10130442,C_934534,2020-03-18 13:50:55,46982.0,0.0,20.0,80.0,1.0,0.58,0.58,...,4.0,17.0,26.250000,1.039721,210339.500000,17,1,2,1,4
4,U_10131901,C_934534,2020-03-18 16:44:39,46985.0,0.0,20.0,80.0,1.0,0.75,0.75,...,6.0,17.0,32.833333,1.011404,208468.666667,17,0,4,2,4